/*
 * 漢字 N4 — First 40 entries from 漢字N4.pdf, expanded to a 400-card deck.
 *
 * Each kanji becomes 10 flashcards:
 *   card 1      : the word by itself ("just the kanji")
 *   cards 2-10  : the word used in a sentence
 *
 * For verbs & adjectives the 9 sentences show 9 grammatical forms, generated by
 * the tested engine in conjugate.js inside a fixed "carrier" phrase (so the
 * Japanese is always correct & natural). For nouns (which don't conjugate) the
 * 9 sentences are hand-authored varied usages, each labelled by its particle/role.
 *
 * RAW entry:
 *   id, word, reading, meaning (Indonesian), meaningEn, type
 *   conjugatable -> carrier:{ pre, preR, mean }   (mean = natural gloss of the phrase)
 *   noun         -> sentences:[ { form, jp, reading, meaning } x9 ]
 */

const RAW = [
  { id: 1, word: "着物", reading: "きもの", meaning: "kimono", meaningEn: "kimono (traditional dress)", type: "noun",
    sentences: [
      { form: "〜を", jp: "着物を着る。", reading: "きものをきる。", meaning: "Memakai kimono. (Wear a kimono.)" },
      { form: "〜が", jp: "着物がきれいだ。", reading: "きものがきれいだ。", meaning: "Kimononya indah. (The kimono is pretty.)" },
      { form: "〜は", jp: "着物は高い。", reading: "きものはたかい。", meaning: "Kimono itu mahal. (Kimono are expensive.)" },
      { form: "〜の", jp: "着物の色。", reading: "きもののいろ。", meaning: "Warna kimono. (The kimono's color.)" },
      { form: "〜を", jp: "着物を買った。", reading: "きものをかった。", meaning: "Membeli kimono. (Bought a kimono.)" },
      { form: "〜で", jp: "着物で行く。", reading: "きものでいく。", meaning: "Pergi memakai kimono. (Go in a kimono.)" },
      { form: "〜に", jp: "着物に興味がある。", reading: "きものにきょうみがある。", meaning: "Tertarik pada kimono. (Interested in kimono.)" },
      { form: "〜を", jp: "着物を着ている。", reading: "きものをきている。", meaning: "Sedang memakai kimono. (Wearing a kimono.)" },
      { form: "〜が", jp: "白い着物がほしい。", reading: "しろいきものがほしい。", meaning: "Ingin kimono putih. (Want a white kimono.)" }
    ] },
  { id: 2, word: "風邪", reading: "かぜ", meaning: "influensa", meaningEn: "a cold (illness)", type: "noun",
    sentences: [
      { form: "〜を", jp: "風邪をひく。", reading: "かぜをひく。", meaning: "Masuk angin. (Catch a cold.)" },
      { form: "〜を", jp: "風邪をひいた。", reading: "かぜをひいた。", meaning: "Kena masuk angin. (Caught a cold.)" },
      { form: "〜が", jp: "風邪が治る。", reading: "かぜがなおる。", meaning: "Sembuh dari flu. (The cold heals.)" },
      { form: "〜で", jp: "風邪で休む。", reading: "かぜでやすむ。", meaning: "Libur karena sakit. (Off due to a cold.)" },
      { form: "〜に", jp: "風邪に気をつけて。", reading: "かぜにきをつけて。", meaning: "Hati-hati jangan masuk angin. (Take care not to catch a cold.)" },
      { form: "〜が", jp: "風邪がなおった。", reading: "かぜがなおった。", meaning: "Sudah sembuh. (The cold got better.)" },
      { form: "〜は", jp: "風邪はつらい。", reading: "かぜはつらい。", meaning: "Flu itu berat. (A cold is rough.)" },
      { form: "〜を", jp: "ひどい風邪をひいた。", reading: "ひどいかぜをひいた。", meaning: "Kena flu parah. (Caught a bad cold.)" },
      { form: "〜の", jp: "風邪の薬。", reading: "かぜのくすり。", meaning: "Obat flu. (Cold medicine.)" }
    ] },
  { id: 3, word: "建物", reading: "たてもの", meaning: "gedung", meaningEn: "building", type: "noun",
    sentences: [
      { form: "〜は", jp: "あの建物は高い。", reading: "あのたてものはたかい。", meaning: "Gedung itu tinggi. (That building is tall.)" },
      { form: "〜が", jp: "建物が見える。", reading: "たてものがみえる。", meaning: "Gedung terlihat. (I can see a building.)" },
      { form: "〜を", jp: "建物を建てる。", reading: "たてものをたてる。", meaning: "Membangun gedung. (Build a building.)" },
      { form: "〜の", jp: "建物の中。", reading: "たてもののなか。", meaning: "Di dalam gedung. (Inside the building.)" },
      { form: "〜に", jp: "建物に入る。", reading: "たてものにはいる。", meaning: "Masuk ke gedung. (Enter the building.)" },
      { form: "〜は", jp: "この建物は古い。", reading: "このたてものはふるい。", meaning: "Gedung ini tua. (This building is old.)" },
      { form: "〜が", jp: "大きい建物がある。", reading: "おおきいたてものがある。", meaning: "Ada gedung besar. (There is a big building.)" },
      { form: "〜を", jp: "建物を出る。", reading: "たてものをでる。", meaning: "Keluar dari gedung. (Leave the building.)" },
      { form: "〜へ", jp: "あの建物へ行く。", reading: "あのたてものへいく。", meaning: "Pergi ke gedung itu. (Go to that building.)" }
    ] },
  { id: 4, word: "台所", reading: "だいどころ", meaning: "dapur", meaningEn: "kitchen", type: "noun",
    sentences: [
      { form: "〜に", jp: "母は台所にいる。", reading: "はははだいどころにいる。", meaning: "Ibu di dapur. (Mom is in the kitchen.)" },
      { form: "〜で", jp: "台所で料理する。", reading: "だいどころでりょうりする。", meaning: "Memasak di dapur. (Cook in the kitchen.)" },
      { form: "〜が", jp: "台所が広い。", reading: "だいどころがひろい。", meaning: "Dapurnya luas. (The kitchen is spacious.)" },
      { form: "〜を", jp: "台所を掃除する。", reading: "だいどころをそうじする。", meaning: "Membersihkan dapur. (Clean the kitchen.)" },
      { form: "〜は", jp: "台所は狭い。", reading: "だいどころはせまい。", meaning: "Dapurnya sempit. (The kitchen is small.)" },
      { form: "〜へ", jp: "台所へ行く。", reading: "だいどころへいく。", meaning: "Pergi ke dapur. (Go to the kitchen.)" },
      { form: "〜の", jp: "台所の窓。", reading: "だいどころのまど。", meaning: "Jendela dapur. (The kitchen window.)" },
      { form: "〜に", jp: "台所に立つ。", reading: "だいどころにたつ。", meaning: "Berdiri di dapur (memasak). (Stand in the kitchen / cook.)" },
      { form: "〜が", jp: "新しい台所がほしい。", reading: "あたらしいだいどころがほしい。", meaning: "Ingin dapur baru. (Want a new kitchen.)" }
    ] },
  { id: 5, word: "品物", reading: "しなもの", meaning: "barang-barang", meaningEn: "goods, articles", type: "noun",
    sentences: [
      { form: "〜は", jp: "この品物は安い。", reading: "このしなものはやすい。", meaning: "Barang ini murah. (These goods are cheap.)" },
      { form: "〜を", jp: "品物を売る。", reading: "しなものをうる。", meaning: "Menjual barang. (Sell goods.)" },
      { form: "〜が", jp: "品物が届いた。", reading: "しなものがとどいた。", meaning: "Barang sudah sampai. (The goods arrived.)" },
      { form: "〜を", jp: "品物を選ぶ。", reading: "しなものをえらぶ。", meaning: "Memilih barang. (Choose goods.)" },
      { form: "〜が", jp: "いい品物がある。", reading: "いいしなものがある。", meaning: "Ada barang bagus. (There are good goods.)" },
      { form: "〜の", jp: "品物の値段。", reading: "しなもののねだん。", meaning: "Harga barang. (The price of the goods.)" },
      { form: "〜は", jp: "品物は多い。", reading: "しなものはおおい。", meaning: "Barangnya banyak. (There are many goods.)" },
      { form: "〜を", jp: "品物を買う。", reading: "しなものをかう。", meaning: "Membeli barang. (Buy goods.)" },
      { form: "〜が", jp: "この品物が人気だ。", reading: "このしなものがにんきだ。", meaning: "Barang ini populer. (These goods are popular.)" }
    ] },
  { id: 6, word: "着く", reading: "つく", meaning: "tiba", meaningEn: "to arrive", type: "godan",
    carrier: { pre: "駅に", preR: "えきに", mean: "Tiba di stasiun (arrive at the station)" } },
  { id: 7, word: "降りる", reading: "おりる", meaning: "turun", meaningEn: "to get off / descend", type: "ichidan",
    carrier: { pre: "バスを", preR: "ばすを", mean: "Turun dari bus (get off the bus)" } },
  { id: 8, word: "動物", reading: "どうぶつ", meaning: "binatang", meaningEn: "animal", type: "noun",
    sentences: [
      { form: "〜が", jp: "動物が好きだ。", reading: "どうぶつがすきだ。", meaning: "Suka binatang. (I like animals.)" },
      { form: "〜園へ", jp: "動物園へ行く。", reading: "どうぶつえんへいく。", meaning: "Pergi ke kebun binatang. (Go to the zoo.)" },
      { form: "〜を", jp: "動物を飼う。", reading: "どうぶつをかう。", meaning: "Memelihara binatang. (Keep an animal.)" },
      { form: "〜が", jp: "森に動物がいる。", reading: "もりにどうぶつがいる。", meaning: "Ada binatang di hutan. (There are animals in the forest.)" },
      { form: "〜は", jp: "動物はかわいい。", reading: "どうぶつはかわいい。", meaning: "Binatang itu lucu. (Animals are cute.)" },
      { form: "〜の", jp: "動物の写真。", reading: "どうぶつのしゃしん。", meaning: "Foto binatang. (An animal photo.)" },
      { form: "〜を", jp: "動物を守る。", reading: "どうぶつをまもる。", meaning: "Melindungi hewan. (Protect animals.)" },
      { form: "〜が", jp: "小さい動物がいる。", reading: "ちいさいどうぶつがいる。", meaning: "Ada hewan kecil. (There is a small animal.)" },
      { form: "〜に", jp: "動物に餌をやる。", reading: "どうぶつにえさをやる。", meaning: "Memberi makan hewan. (Feed the animals.)" }
    ] },
  { id: 9, word: "台風", reading: "たいふう", meaning: "angin topan", meaningEn: "typhoon", type: "noun",
    sentences: [
      { form: "〜が", jp: "台風が来る。", reading: "たいふうがくる。", meaning: "Topan datang. (A typhoon is coming.)" },
      { form: "〜が", jp: "台風が近づく。", reading: "たいふうがちかづく。", meaning: "Topan mendekat. (A typhoon approaches.)" },
      { form: "〜で", jp: "台風で電車が止まる。", reading: "たいふうででんしゃがとまる。", meaning: "Kereta berhenti karena topan. (Trains stop due to the typhoon.)" },
      { form: "〜は", jp: "台風は強い。", reading: "たいふうはつよい。", meaning: "Topannya kuat. (The typhoon is strong.)" },
      { form: "〜が", jp: "台風が過ぎた。", reading: "たいふうがすぎた。", meaning: "Topan sudah lewat. (The typhoon passed.)" },
      { form: "〜の", jp: "台風の日。", reading: "たいふうのひ。", meaning: "Hari ada topan. (A typhoon day.)" },
      { form: "〜に", jp: "台風に気をつけて。", reading: "たいふうにきをつけて。", meaning: "Hati-hati dengan topan. (Watch out for the typhoon.)" },
      { form: "〜が", jp: "大きい台風が来た。", reading: "おおきいたいふうがきた。", meaning: "Topan besar datang. (A big typhoon came.)" },
      { form: "〜で", jp: "台風で休みだ。", reading: "たいふうでやすみだ。", meaning: "Libur karena topan. (Off because of the typhoon.)" }
    ] },
  { id: 10, word: "輸入する", reading: "ゆにゅうする", meaning: "import", meaningEn: "to import", type: "suru",
    carrier: { pre: "車を", preR: "くるまを", mean: "Mengimpor mobil (import a car)" } },
  { id: 11, word: "輸出する", reading: "ゆしゅつする", meaning: "eksport", meaningEn: "to export", type: "suru",
    carrier: { pre: "米を", preR: "こめを", mean: "Mengekspor beras (export rice)" } },
  { id: 12, word: "建てる", reading: "たてる", meaning: "mendirikan", meaningEn: "to build", type: "ichidan",
    carrier: { pre: "家を", preR: "いえを", mean: "Membangun rumah (build a house)" } },
  { id: 13, word: "荷物", reading: "にもつ", meaning: "barang bawaan", meaningEn: "luggage, baggage", type: "noun",
    sentences: [
      { form: "〜が", jp: "荷物が重い。", reading: "にもつがおもい。", meaning: "Bawaan berat. (The luggage is heavy.)" },
      { form: "〜を", jp: "荷物を持つ。", reading: "にもつをもつ。", meaning: "Membawa barang. (Carry the luggage.)" },
      { form: "〜を", jp: "荷物を送る。", reading: "にもつをおくる。", meaning: "Mengirim paket. (Send a parcel.)" },
      { form: "〜が", jp: "荷物が届いた。", reading: "にもつがとどいた。", meaning: "Paket sudah sampai. (The parcel arrived.)" },
      { form: "〜は", jp: "荷物は多い。", reading: "にもつはおおい。", meaning: "Barangnya banyak. (There's a lot of luggage.)" },
      { form: "〜を", jp: "荷物を運ぶ。", reading: "にもつをはこぶ。", meaning: "Mengangkut barang. (Carry the luggage.)" },
      { form: "〜の", jp: "荷物の中。", reading: "にもつのなか。", meaning: "Di dalam bagasi. (Inside the luggage.)" },
      { form: "〜を", jp: "重い荷物を持つ。", reading: "おもいにもつをもつ。", meaning: "Membawa barang berat. (Carry heavy luggage.)" },
      { form: "〜が", jp: "荷物が多すぎる。", reading: "にもつがおおすぎる。", meaning: "Barangnya terlalu banyak. (Too much luggage.)" }
    ] },
  { id: 14, word: "着る", reading: "きる", meaning: "memakai, mengenakan", meaningEn: "to wear (upper body)", type: "ichidan",
    carrier: { pre: "服を", preR: "ふくを", mean: "Memakai baju (wear clothes)" } },
  { id: 15, word: "通る", reading: "とおる", meaning: "melewati", meaningEn: "to pass through", type: "godan",
    carrier: { pre: "道を", preR: "みちを", mean: "Melewati jalan (pass along the road)" } },
  { id: 16, word: "普通", reading: "ふつう", meaning: "biasa", meaningEn: "normal, ordinary", type: "noun",
    sentences: [
      { form: "〜の", jp: "普通の日だ。", reading: "ふつうのひだ。", meaning: "Hari biasa. (An ordinary day.)" },
      { form: "〜に", jp: "普通に話す。", reading: "ふつうにはなす。", meaning: "Berbicara biasa saja. (Speak normally.)" },
      { form: "〜は", jp: "普通はそうする。", reading: "ふつうはそうする。", meaning: "Biasanya begitu. (Usually you do that.)" },
      { form: "〜の", jp: "普通の人。", reading: "ふつうのひと。", meaning: "Orang biasa. (An ordinary person.)" },
      { form: "〜だ", jp: "これは普通だ。", reading: "これはふつうだ。", meaning: "Ini biasa. (This is normal.)" },
      { form: "〜の", jp: "普通の生活。", reading: "ふつうのせいかつ。", meaning: "Kehidupan biasa. (An ordinary life.)" },
      { form: "〜に", jp: "普通に食べる。", reading: "ふつうにたべる。", meaning: "Makan seperti biasa. (Eat normally.)" },
      { form: "〜は", jp: "普通は無料だ。", reading: "ふつうはむりょうだ。", meaning: "Biasanya gratis. (Usually it's free.)" },
      { form: "〜の", jp: "普通の値段。", reading: "ふつうのねだん。", meaning: "Harga normal. (A normal price.)" }
    ] },
  { id: 17, word: "交通", reading: "こうつう", meaning: "transportasi", meaningEn: "traffic, transport", type: "noun",
    sentences: [
      { form: "〜が", jp: "交通が便利だ。", reading: "こうつうがべんりだ。", meaning: "Transportasi praktis. (Transport is convenient.)" },
      { form: "〜が", jp: "交通が多い。", reading: "こうつうがおおい。", meaning: "Lalu lintas padat. (There is a lot of traffic.)" },
      { form: "〜の", jp: "交通の便。", reading: "こうつうのべん。", meaning: "Kemudahan transportasi. (Transport access.)" },
      { form: "〜は", jp: "交通は不便だ。", reading: "こうつうはふべんだ。", meaning: "Transportasinya tidak nyaman. (Transport is inconvenient.)" },
      { form: "〜が", jp: "交通が止まる。", reading: "こうつうがとまる。", meaning: "Lalu lintas berhenti. (Traffic stops.)" },
      { form: "〜の", jp: "交通のルール。", reading: "こうつうのるーる。", meaning: "Aturan lalu lintas. (Traffic rules.)" },
      { form: "〜に", jp: "交通に気をつける。", reading: "こうつうにきをつける。", meaning: "Hati-hati di lalu lintas. (Be careful of traffic.)" },
      { form: "〜が", jp: "朝は交通が多い。", reading: "あさはこうつうがおおい。", meaning: "Pagi lalu lintas padat. (Traffic is heavy in the morning.)" },
      { form: "〜事故", jp: "交通事故に注意。", reading: "こうつうじこにちゅうい。", meaning: "Awas kecelakaan lalu lintas. (Beware traffic accidents.)" }
    ] },
  { id: 18, word: "通う", reading: "かよう", meaning: "bolak-balik", meaningEn: "to commute / attend regularly", type: "godan",
    carrier: { pre: "学校に", preR: "がっこうに", mean: "Pergi ke sekolah rutin (commute to school)" } },
  { id: 19, word: "集まる", reading: "あつまる", meaning: "berkumpul", meaningEn: "to gather (intransitive)", type: "godan",
    carrier: { pre: "人が", preR: "ひとが", mean: "Orang berkumpul (people gather)" } },
  { id: 20, word: "便利な", reading: "べんりな", meaning: "praktis", meaningEn: "convenient", type: "na-adj",
    carrier: { pre: "この店は", preR: "このみせは", mean: "Toko ini praktis (this shop is convenient)" } },
  { id: 21, word: "同じ", reading: "おなじ", meaning: "sama", meaningEn: "same", type: "noun",
    sentences: [
      { form: "〜だ", jp: "同じ本だ。", reading: "おなじほんだ。", meaning: "Buku yang sama. (It's the same book.)" },
      { form: "〜クラス", jp: "同じクラスだ。", reading: "おなじくらすだ。", meaning: "Sekelas. (We're in the same class.)" },
      { form: "〜だ", jp: "意見が同じだ。", reading: "いけんがおなじだ。", meaning: "Pendapatnya sama. (The opinions are the same.)" },
      { form: "〜物", jp: "同じ物を買う。", reading: "おなじものをかう。", meaning: "Beli barang yang sama. (Buy the same thing.)" },
      { form: "〜時間", jp: "同じ時間に来る。", reading: "おなじじかんにくる。", meaning: "Datang di waktu yang sama. (Come at the same time.)" },
      { form: "〜だ", jp: "私も同じだ。", reading: "わたしもおなじだ。", meaning: "Saya juga sama. (I'm the same too.)" },
      { form: "〜人", jp: "同じ人だ。", reading: "おなじひとだ。", meaning: "Orang yang sama. (It's the same person.)" },
      { form: "〜だ", jp: "答えは同じだ。", reading: "こたえはおなじだ。", meaning: "Jawabannya sama. (The answer is the same.)" },
      { form: "〜町", jp: "同じ町に住む。", reading: "おなじまちにすむ。", meaning: "Tinggal di kota yang sama. (Live in the same town.)" }
    ] },
  { id: 22, word: "毎晩", reading: "まいばん", meaning: "setiap malam", meaningEn: "every night", type: "noun",
    sentences: [
      { form: "〜勉強", jp: "毎晩勉強する。", reading: "まいばんべんきょうする。", meaning: "Belajar setiap malam. (Study every night.)" },
      { form: "〜テレビ", jp: "毎晩テレビを見る。", reading: "まいばんてれびをみる。", meaning: "Nonton TV tiap malam. (Watch TV every night.)" },
      { form: "〜寝る", jp: "毎晩早く寝る。", reading: "まいばんはやくねる。", meaning: "Tidur cepat tiap malam. (Sleep early every night.)" },
      { form: "〜読む", jp: "毎晩本を読む。", reading: "まいばんほんをよむ。", meaning: "Baca buku tiap malam. (Read a book every night.)" },
      { form: "〜散歩", jp: "毎晩散歩する。", reading: "まいばんさんぽする。", meaning: "Jalan-jalan tiap malam. (Take a walk every night.)" },
      { form: "〜電話", jp: "毎晩電話する。", reading: "まいばんでんわする。", meaning: "Menelepon tiap malam. (Call every night.)" },
      { form: "〜風呂", jp: "毎晩お風呂に入る。", reading: "まいばんおふろにはいる。", meaning: "Mandi tiap malam. (Take a bath every night.)" },
      { form: "〜日記", jp: "毎晩日記を書く。", reading: "まいばんにっきをかく。", meaning: "Menulis diari tiap malam. (Write a diary every night.)" },
      { form: "〜働く", jp: "毎晩遅くまで働く。", reading: "まいばんおそくまではたらく。", meaning: "Kerja sampai malam tiap hari. (Work late every night.)" }
    ] },
  { id: 23, word: "使う", reading: "つかう", meaning: "menggunakan", meaningEn: "to use", type: "godan",
    carrier: { pre: "箸を", preR: "はしを", mean: "Memakai sumpit (use chopsticks)" } },
  { id: 24, word: "進む", reading: "すすむ", meaning: "memajukan, meningkatkan", meaningEn: "to advance, proceed", type: "godan",
    carrier: { pre: "前に", preR: "まえに", mean: "Maju ke depan (move forward)" } },
  { id: 25, word: "作る", reading: "つくる", meaning: "membuat", meaningEn: "to make", type: "godan",
    carrier: { pre: "料理を", preR: "りょうりを", mean: "Membuat masakan (make food)" } },
  { id: 26, word: "今晩", reading: "こんばん", meaning: "malam ini", meaningEn: "tonight", type: "noun",
    sentences: [
      { form: "〜は", jp: "今晩は暇だ。", reading: "こんばんはひまだ。", meaning: "Malam ini senggang. (I'm free tonight.)" },
      { form: "〜会う", jp: "今晩会おう。", reading: "こんばんあおう。", meaning: "Ketemu malam ini. (Let's meet tonight.)" },
      { form: "〜何", jp: "今晩何を食べる？", reading: "こんばんなにをたべる？", meaning: "Malam ini makan apa? (What will you eat tonight?)" },
      { form: "〜雨", jp: "今晩雨が降る。", reading: "こんばんあめがふる。", meaning: "Malam ini hujan. (It will rain tonight.)" },
      { form: "〜勉強", jp: "今晩勉強する。", reading: "こんばんべんきょうする。", meaning: "Belajar malam ini. (Study tonight.)" },
      { form: "〜は", jp: "今晩は寒い。", reading: "こんばんはさむい。", meaning: "Malam ini dingin. (It's cold tonight.)" },
      { form: "〜映画", jp: "今晩映画を見る。", reading: "こんばんえいがをみる。", meaning: "Nonton film malam ini. (Watch a movie tonight.)" },
      { form: "〜帰る", jp: "今晩早く帰る。", reading: "こんばんはやくかえる。", meaning: "Pulang cepat malam ini. (Go home early tonight.)" },
      { form: "〜電話", jp: "今晩電話するね。", reading: "こんばんでんわするね。", meaning: "Nanti malam kutelepon. (I'll call tonight.)" }
    ] },
  { id: 27, word: "勉強する", reading: "べんきょうする", meaning: "belajar", meaningEn: "to study", type: "suru",
    carrier: { pre: "日本語を", preR: "にほんごを", mean: "Belajar bahasa Jepang (study Japanese)" } },
  { id: 28, word: "文章", reading: "ぶんしょう", meaning: "kalimat", meaningEn: "sentence, writing", type: "noun",
    sentences: [
      { form: "〜を", jp: "文章を書く。", reading: "ぶんしょうをかく。", meaning: "Menulis tulisan. (Write a text.)" },
      { form: "〜が", jp: "文章が長い。", reading: "ぶんしょうがながい。", meaning: "Tulisannya panjang. (The text is long.)" },
      { form: "〜を", jp: "文章を読む。", reading: "ぶんしょうをよむ。", meaning: "Membaca teks. (Read the text.)" },
      { form: "〜が", jp: "文章が難しい。", reading: "ぶんしょうがむずかしい。", meaning: "Teksnya sulit. (The text is difficult.)" },
      { form: "〜を", jp: "文章を直す。", reading: "ぶんしょうをなおす。", meaning: "Memperbaiki tulisan. (Fix the text.)" },
      { form: "〜だ", jp: "短い文章だ。", reading: "みじかいぶんしょうだ。", meaning: "Kalimat pendek. (It's a short text.)" },
      { form: "〜の", jp: "文章の意味。", reading: "ぶんしょうのいみ。", meaning: "Arti teks. (The meaning of the text.)" },
      { form: "〜を", jp: "きれいな文章を書く。", reading: "きれいなぶんしょうをかく。", meaning: "Menulis tulisan rapi. (Write clean prose.)" },
      { form: "〜が", jp: "文章がわかりやすい。", reading: "ぶんしょうがわかりやすい。", meaning: "Teksnya mudah dipahami. (The text is easy to understand.)" }
    ] },
  { id: 29, word: "作文", reading: "さくぶん", meaning: "karangan", meaningEn: "composition, essay", type: "noun",
    sentences: [
      { form: "〜が", jp: "作文が難しい。", reading: "さくぶんがむずかしい。", meaning: "Karangan sulit. (The essay is hard.)" },
      { form: "〜を", jp: "作文を書く。", reading: "さくぶんをかく。", meaning: "Menulis karangan. (Write a composition.)" },
      { form: "〜の", jp: "作文の宿題。", reading: "さくぶんのしゅくだい。", meaning: "PR mengarang. (Essay homework.)" },
      { form: "〜を", jp: "作文を出す。", reading: "さくぶんをだす。", meaning: "Menyerahkan karangan. (Hand in the essay.)" },
      { form: "〜で", jp: "日本語で作文を書く。", reading: "にほんごでさくぶんをかく。", meaning: "Menulis karangan dlm bhs Jepang. (Write an essay in Japanese.)" },
      { form: "〜が", jp: "作文が上手だ。", reading: "さくぶんがじょうずだ。", meaning: "Pandai mengarang. (Good at essays.)" },
      { form: "〜を", jp: "作文を直す。", reading: "さくぶんをなおす。", meaning: "Memperbaiki karangan. (Correct the essay.)" },
      { form: "〜を", jp: "作文を読む。", reading: "さくぶんをよむ。", meaning: "Membaca karangan. (Read the essay.)" },
      { form: "〜だ", jp: "長い作文だ。", reading: "ながいさくぶんだ。", meaning: "Karangan yang panjang. (It's a long essay.)" }
    ] },
  { id: 30, word: "大使館", reading: "たいしかん", meaning: "kedutaan", meaningEn: "embassy", type: "noun",
    sentences: [
      { form: "〜へ", jp: "大使館へ行く。", reading: "たいしかんへいく。", meaning: "Pergi ke kedutaan. (Go to the embassy.)" },
      { form: "〜で", jp: "大使館で働く。", reading: "たいしかんではたらく。", meaning: "Bekerja di kedutaan. (Work at the embassy.)" },
      { form: "〜に", jp: "大使館に電話する。", reading: "たいしかんにでんわする。", meaning: "Menelepon kedutaan. (Call the embassy.)" },
      { form: "〜は", jp: "大使館は近い。", reading: "たいしかんはちかい。", meaning: "Kedutaannya dekat. (The embassy is near.)" },
      { form: "〜を", jp: "日本大使館を探す。", reading: "にほんたいしかんをさがす。", meaning: "Mencari kedutaan Jepang. (Look for the Japanese embassy.)" },
      { form: "〜の", jp: "大使館の前。", reading: "たいしかんのまえ。", meaning: "Depan kedutaan. (In front of the embassy.)" },
      { form: "〜に", jp: "大使館に着く。", reading: "たいしかんにつく。", meaning: "Tiba di kedutaan. (Arrive at the embassy.)" },
      { form: "〜が", jp: "大使館が閉まる。", reading: "たいしかんがしまる。", meaning: "Kedutaan tutup. (The embassy closes.)" },
      { form: "〜で", jp: "大使館で書類を出す。", reading: "たいしかんでしょるいをだす。", meaning: "Menyerahkan dokumen di kedutaan. (Submit documents at the embassy.)" }
    ] },
  { id: 31, word: "郵便局", reading: "ゆうびんきょく", meaning: "kantor pos", meaningEn: "post office", type: "noun",
    sentences: [
      { form: "〜で", jp: "郵便局で働く。", reading: "ゆうびんきょくではたらく。", meaning: "Bekerja di kantor pos. (Work at the post office.)" },
      { form: "〜へ", jp: "郵便局へ行く。", reading: "ゆうびんきょくへいく。", meaning: "Pergi ke kantor pos. (Go to the post office.)" },
      { form: "〜は", jp: "郵便局は近い。", reading: "ゆうびんきょくはちかい。", meaning: "Kantor pos dekat. (The post office is near.)" },
      { form: "〜で", jp: "郵便局で切手を買う。", reading: "ゆうびんきょくできってをかう。", meaning: "Beli perangko di kantor pos. (Buy stamps at the post office.)" },
      { form: "〜に", jp: "郵便局に荷物を出す。", reading: "ゆうびんきょくににもつをだす。", meaning: "Kirim paket di kantor pos. (Send a parcel at the post office.)" },
      { form: "〜の", jp: "郵便局の前で待つ。", reading: "ゆうびんきょくのまえでまつ。", meaning: "Menunggu di depan kantor pos. (Wait in front of the post office.)" },
      { form: "〜が", jp: "郵便局が閉まる。", reading: "ゆうびんきょくがしまる。", meaning: "Kantor pos tutup. (The post office closes.)" },
      { form: "〜は", jp: "郵便局はどこですか。", reading: "ゆうびんきょくはどこですか。", meaning: "Di mana kantor pos? (Where is the post office?)" },
      { form: "〜で", jp: "郵便局でお金を送る。", reading: "ゆうびんきょくでおかねをおくる。", meaning: "Kirim uang di kantor pos. (Send money at the post office.)" }
    ] },
  { id: 32, word: "最近", reading: "さいきん", meaning: "baru-baru ini", meaningEn: "recently, lately", type: "noun",
    sentences: [
      { form: "〜忙しい", jp: "最近忙しい。", reading: "さいきんいそがしい。", meaning: "Akhir-akhir ini sibuk. (I've been busy lately.)" },
      { form: "〜寒い", jp: "最近寒い。", reading: "さいきんさむい。", meaning: "Belakangan dingin. (It's been cold lately.)" },
      { form: "〜見た", jp: "最近映画を見た。", reading: "さいきんえいがをみた。", meaning: "Baru-baru ini nonton film. (I watched a movie recently.)" },
      { form: "〜元気", jp: "最近元気だ。", reading: "さいきんげんきだ。", meaning: "Belakangan sehat. (I've been well lately.)" },
      { form: "〜勉強", jp: "最近日本語を勉強している。", reading: "さいきんにほんごをべんきょうしている。", meaning: "Belakangan belajar bhs Jepang. (I've been studying Japanese lately.)" },
      { form: "〜雨", jp: "最近雨が多い。", reading: "さいきんあめがおおい。", meaning: "Belakangan sering hujan. (It's rained a lot lately.)" },
      { form: "〜会わない", jp: "最近彼に会わない。", reading: "さいきんかれにあわない。", meaning: "Belakangan tak bertemu dia. (I haven't seen him lately.)" },
      { form: "〜どう", jp: "最近どうですか。", reading: "さいきんどうですか。", meaning: "Bagaimana belakangan ini? (How have you been lately?)" },
      { form: "〜引っ越した", jp: "最近引っ越した。", reading: "さいきんひっこした。", meaning: "Baru-baru ini pindah. (I moved recently.)" }
    ] },
  { id: 33, word: "明日", reading: "あした", meaning: "besok", meaningEn: "tomorrow", type: "noun",
    sentences: [
      { form: "〜会う", jp: "明日会おう。", reading: "あしたあおう。", meaning: "Ketemu besok. (Let's meet tomorrow.)" },
      { form: "〜は", jp: "明日は休みだ。", reading: "あしたはやすみだ。", meaning: "Besok libur. (Tomorrow is a day off.)" },
      { form: "〜雨", jp: "明日雨が降る。", reading: "あしたあめがふる。", meaning: "Besok hujan. (It will rain tomorrow.)" },
      { form: "〜試験", jp: "明日試験がある。", reading: "あしたしけんがある。", meaning: "Besok ada ujian. (There's a test tomorrow.)" },
      { form: "〜来る", jp: "明日また来る。", reading: "あしたまたくる。", meaning: "Besok datang lagi. (I'll come again tomorrow.)" },
      { form: "〜の", jp: "明日の予定。", reading: "あしたのよてい。", meaning: "Rencana besok. (Tomorrow's plans.)" },
      { form: "〜起きる", jp: "明日早く起きる。", reading: "あしたはやくおきる。", meaning: "Besok bangun pagi. (Get up early tomorrow.)" },
      { form: "〜電話", jp: "明日電話する。", reading: "あしたでんわする。", meaning: "Besok menelepon. (I'll call tomorrow.)" },
      { form: "〜は", jp: "明日は忙しい。", reading: "あしたはいそがしい。", meaning: "Besok sibuk. (I'm busy tomorrow.)" }
    ] },
  { id: 34, word: "遠足", reading: "えんそく", meaning: "perjalanan/trip", meaningEn: "excursion, field trip", type: "noun",
    sentences: [
      { form: "〜に", jp: "遠足に行く。", reading: "えんそくにいく。", meaning: "Pergi tamasya. (Go on an excursion.)" },
      { form: "〜が", jp: "遠足が楽しみだ。", reading: "えんそくがたのしみだ。", meaning: "Menantikan darmawisata. (Looking forward to the trip.)" },
      { form: "〜は", jp: "遠足は明日だ。", reading: "えんそくはあしただ。", meaning: "Tamasyanya besok. (The excursion is tomorrow.)" },
      { form: "〜の", jp: "遠足の日。", reading: "えんそくのひ。", meaning: "Hari tamasya. (Excursion day.)" },
      { form: "〜で", jp: "遠足でお弁当を食べる。", reading: "えんそくでおべんとうをたべる。", meaning: "Makan bekal saat tamasya. (Eat a bento on the trip.)" },
      { form: "〜が", jp: "遠足が中止だ。", reading: "えんそくがちゅうしだ。", meaning: "Tamasya dibatalkan. (The excursion is cancelled.)" },
      { form: "〜の", jp: "学校の遠足。", reading: "がっこうのえんそく。", meaning: "Tamasya sekolah. (A school excursion.)" },
      { form: "〜に", jp: "遠足に行きたい。", reading: "えんそくにいきたい。", meaning: "Ingin ikut tamasya. (I want to go on the trip.)" },
      { form: "〜だった", jp: "楽しい遠足だった。", reading: "たのしいえんそくだった。", meaning: "Tamasya yang menyenangkan. (It was a fun excursion.)" }
    ] },
  { id: 35, word: "説明", reading: "せつめい", meaning: "penjelasan", meaningEn: "explanation", type: "noun",
    sentences: [
      { form: "〜を", jp: "説明を聞く。", reading: "せつめいをきく。", meaning: "Mendengar penjelasan. (Listen to the explanation.)" },
      { form: "〜する", jp: "説明する。", reading: "せつめいする。", meaning: "Menjelaskan. (Explain.)" },
      { form: "〜が", jp: "説明が分かりやすい。", reading: "せつめいがわかりやすい。", meaning: "Penjelasannya mudah dimengerti. (The explanation is clear.)" },
      { form: "〜を", jp: "説明を読む。", reading: "せつめいをよむ。", meaning: "Membaca penjelasan. (Read the explanation.)" },
      { form: "〜の", jp: "先生の説明。", reading: "せんせいのせつめい。", meaning: "Penjelasan guru. (The teacher's explanation.)" },
      { form: "〜が", jp: "説明が長い。", reading: "せつめいがながい。", meaning: "Penjelasannya panjang. (The explanation is long.)" },
      { form: "〜を", jp: "説明をお願いします。", reading: "せつめいをおねがいします。", meaning: "Tolong dijelaskan. (Please explain.)" },
      { form: "〜が", jp: "説明が足りない。", reading: "せつめいがたりない。", meaning: "Penjelasannya kurang. (The explanation is insufficient.)" },
      { form: "〜だ", jp: "詳しい説明だ。", reading: "くわしいせつめいだ。", meaning: "Penjelasan rinci. (It's a detailed explanation.)" }
    ] },
  { id: 36, word: "近所", reading: "きんじょ", meaning: "tetangga", meaningEn: "neighborhood", type: "noun",
    sentences: [
      { form: "〜に", jp: "近所に住む。", reading: "きんじょにすむ。", meaning: "Tinggal di dekat sini. (Live nearby.)" },
      { form: "〜を", jp: "近所を散歩する。", reading: "きんじょをさんぽする。", meaning: "Jalan-jalan di sekitar rumah. (Walk around the neighborhood.)" },
      { form: "〜の", jp: "近所のお店。", reading: "きんじょのおみせ。", meaning: "Toko dekat rumah. (A local shop.)" },
      { form: "〜は", jp: "近所は静かだ。", reading: "きんじょはしずかだ。", meaning: "Lingkungannya tenang. (The neighborhood is quiet.)" },
      { form: "〜に", jp: "近所に公園がある。", reading: "きんじょにこうえんがある。", meaning: "Ada taman di dekat sini. (There's a park nearby.)" },
      { form: "〜の", jp: "近所の人。", reading: "きんじょのひと。", meaning: "Tetangga. (A neighbor.)" },
      { form: "〜で", jp: "近所で買い物する。", reading: "きんじょでかいものする。", meaning: "Belanja di dekat rumah. (Shop nearby.)" },
      { form: "〜に", jp: "近所に引っ越す。", reading: "きんじょにひっこす。", meaning: "Pindah ke dekat sini. (Move to the neighborhood.)" },
      { form: "〜が", jp: "近所が便利だ。", reading: "きんじょがべんりだ。", meaning: "Lingkungannya praktis. (The area is convenient.)" }
    ] },
  { id: 37, word: "短い", reading: "みじかい", meaning: "pendek", meaningEn: "short", type: "i-adj",
    carrier: { pre: "髪が", preR: "かみが", mean: "Rambut pendek (the hair is short)" } },
  { id: 38, word: "弱い", reading: "よわい", meaning: "lemah", meaningEn: "weak", type: "i-adj",
    carrier: { pre: "体が", preR: "からだが", mean: "Badan lemah (the body is weak)" } },
  { id: 39, word: "遠い", reading: "とおい", meaning: "jauh", meaningEn: "far", type: "i-adj",
    carrier: { pre: "駅が", preR: "えきが", mean: "Stasiun jauh (the station is far)" } },
  { id: 40, word: "強い", reading: "つよい", meaning: "kuat, kencang", meaningEn: "strong", type: "i-adj",
    carrier: { pre: "風が", preR: "かぜが", mean: "Angin kencang (the wind is strong)" } }
];

const TYPE_LABELS = {
  "noun": "Noun",
  "godan": "Verb (godan / u)",
  "ichidan": "Verb (ichidan / ru)",
  "suru": "Verb (suru)",
  "i-adj": "い-adjective",
  "na-adj": "な-adjective"
};

const CONJUGATABLE = new Set(["godan", "ichidan", "suru", "i-adj", "na-adj"]);

// ---- Flatten RAW into the 400-card deck -------------------------------------
function buildCards() {
  const out = [];
  for (const e of RAW) {
    const meta = { kanjiId: e.id, word: e.word, reading: e.reading, meaning: e.meaning, meaningEn: e.meaningEn, type: e.type };

    // Card 1: just the kanji. audioFile is a stable name (kanjiId-slot) shared
    // by the pre-rendered audio pipeline (scripts/generate-audio.js) and the
    // browser player (app.js), so both sides agree on filenames without
    // either one recomputing indices independently.
    out.push(Object.assign({}, meta, { mode: "isolated", audioFile: `${e.id}-0.m4a`, audioText: e.word }));

    // Cards 2-10: in a sentence
    if (e.type === "noun") {
      e.sentences.forEach((s, i) => {
        out.push(Object.assign({}, meta, {
          mode: "sentence", form: s.form, jp: s.jp, sentReading: s.reading,
          sentMeaning: s.meaning, target: e.word, targetKana: e.reading,
          audioFile: `${e.id}-${i + 1}.m4a`, audioText: s.jp
        }));
      });
    } else {
      conjugate(e.word, e.reading, e.type).forEach((f, i) => {
        const jp = e.carrier.pre + f.disp + "。";
        out.push(Object.assign({}, meta, {
          mode: "sentence", form: f.label,
          jp, sentReading: e.carrier.preR + f.kana + "。",
          sentMeaning: e.carrier.mean + (FORM_MEANING_TAG[f.key] || ""),
          target: f.disp, targetKana: f.kana,
          audioFile: `${e.id}-${i + 1}.m4a`, audioText: jp
        }));
      });
    }
  }
  return out;
}

const CARDS = buildCards();

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CARDS, RAW, TYPE_LABELS, CONJUGATABLE };
}
