/*
 * kotd-data.js — hand-authored N4/N5 kanji dataset for "Kanji of the Day"
 * (kotd.html / kotd.js). Distinct from data.js, which is word-level.
 *
 * Level tags follow the standard old-JLPT Level 4/3 -> N5/N4 kanji split
 * used across most study references. A handful of very common everyday
 * kanji (colors, vehicles, some family/place words) sit right on that
 * boundary and different publishers place them a level apart — treat the
 * N5/N4 split here as a reasonable, commonly-used convention rather than
 * a single official source of truth.
 *
 * RAW entry shapes:
 *   type: "single"   -> { id, type, kanji, onyomi, kunyomi, meaning, meaningEn, level, example }
 *   type: "compound" -> { id, type, word, reading, meaning, meaningEn, level, parts: [id, id, ...], example }
 *     - onyomi/kunyomi: kana strings ("" if none for that reading type)
 *     - meaning: Indonesian gloss; meaningEn: English gloss
 *     - level: "N5" | "N4"
 *     - example: { jp, reading, meaning } — meaning is "Indonesian. (English.)"
 *     - parts (compound only): ids of the "single" entries the word is built from,
 *       used by kotd.js to render a "built from X + Y" breakdown
 *
 * `id` is a stable key independent of array position — used by kotd.js's
 * daily-rotation math and by compound entries' `parts` references.
 */
const RAW = [
  { id: 1, type: "single", kanji: "一", onyomi: "イチ", kunyomi: "ひと(つ)", meaning: "satu", meaningEn: "one", level: "N5",
    example: { jp: "りんごを一つ食べます。", reading: "りんごをひとつたべます。", meaning: "Makan satu buah apel. (Eat one apple.)" } },
  { id: 2, type: "single", kanji: "二", onyomi: "ニ", kunyomi: "ふた(つ)", meaning: "dua", meaningEn: "two", level: "N5",
    example: { jp: "二人で映画を見ます。", reading: "ふたりでえいがをみます。", meaning: "Menonton film berdua. (Watch a movie, two people.)" } },
  { id: 3, type: "single", kanji: "三", onyomi: "サン", kunyomi: "みっ(つ)", meaning: "tiga", meaningEn: "three", level: "N5",
    example: { jp: "三時に会いましょう。", reading: "さんじにあいましょう。", meaning: "Ayo bertemu jam tiga. (Let's meet at three o'clock.)" } },
  { id: 4, type: "single", kanji: "四", onyomi: "シ・ヨン", kunyomi: "よっ(つ)", meaning: "empat", meaningEn: "four", level: "N5",
    example: { jp: "四月に日本へ行きます。", reading: "しがつににほんへいきます。", meaning: "Pergi ke Jepang bulan April. (Go to Japan in April.)" } },
  { id: 5, type: "single", kanji: "五", onyomi: "ゴ", kunyomi: "いつ(つ)", meaning: "lima", meaningEn: "five", level: "N5",
    example: { jp: "五分待ってください。", reading: "ごふんまってください。", meaning: "Tolong tunggu lima menit. (Please wait five minutes.)" } },
  { id: 6, type: "single", kanji: "六", onyomi: "ロク", kunyomi: "むっ(つ)", meaning: "enam", meaningEn: "six", level: "N5",
    example: { jp: "六時に起きます。", reading: "ろくじにおきます。", meaning: "Bangun jam enam. (Wake up at six o'clock.)" } },
  { id: 7, type: "single", kanji: "七", onyomi: "シチ・ナナ", kunyomi: "なな(つ)", meaning: "tujuh", meaningEn: "seven", level: "N5",
    example: { jp: "七月は暑いです。", reading: "しちがつはあついです。", meaning: "Bulan Juli panas. (July is hot.)" } },
  { id: 8, type: "single", kanji: "八", onyomi: "ハチ", kunyomi: "やっ(つ)", meaning: "delapan", meaningEn: "eight", level: "N5",
    example: { jp: "八時に寝ます。", reading: "はちじにねます。", meaning: "Tidur jam delapan. (Go to bed at eight.)" } },
  { id: 9, type: "single", kanji: "九", onyomi: "キュウ・ク", kunyomi: "ここの(つ)", meaning: "sembilan", meaningEn: "nine", level: "N5",
    example: { jp: "九月に学校が始まります。", reading: "くがつにがっこうがはじまります。", meaning: "Sekolah mulai bulan September. (School starts in September.)" } },
  { id: 10, type: "single", kanji: "十", onyomi: "ジュウ", kunyomi: "とお", meaning: "sepuluh", meaningEn: "ten", level: "N5",
    example: { jp: "十年前に結婚しました。", reading: "じゅうねんまえにけっこんしました。", meaning: "Menikah sepuluh tahun lalu. (Got married ten years ago.)" } },
  { id: 11, type: "single", kanji: "百", onyomi: "ヒャク", kunyomi: "", meaning: "seratus", meaningEn: "hundred", level: "N5",
    example: { jp: "りんごを百個買いました。", reading: "りんごをひゃっこかいました。", meaning: "Membeli seratus buah apel. (Bought a hundred apples.)" } },
  { id: 12, type: "single", kanji: "千", onyomi: "セン", kunyomi: "", meaning: "seribu", meaningEn: "thousand", level: "N5",
    example: { jp: "千円貸してください。", reading: "せんえんかしてください。", meaning: "Tolong pinjamkan seribu yen. (Please lend me a thousand yen.)" } },
  { id: 13, type: "single", kanji: "万", onyomi: "マン", kunyomi: "", meaning: "sepuluh ribu", meaningEn: "ten thousand", level: "N5",
    example: { jp: "この車は百万円です。", reading: "このくるまはひゃくまんえんです。", meaning: "Mobil ini seharga satu juta yen. (This car costs one million yen.)" } },
  { id: 14, type: "single", kanji: "円", onyomi: "エン", kunyomi: "", meaning: "yen", meaningEn: "yen", level: "N5",
    example: { jp: "この本は五百円です。", reading: "このほんはごひゃくえんです。", meaning: "Buku ini lima ratus yen. (This book is five hundred yen.)" } },
  { id: 15, type: "single", kanji: "日", onyomi: "ニチ・ジツ", kunyomi: "ひ・か", meaning: "hari, matahari", meaningEn: "day, sun", level: "N5",
    example: { jp: "今日はいい天気です。", reading: "きょうはいいてんきです。", meaning: "Hari ini cuacanya bagus. (Today's weather is nice.)" } },
  { id: 16, type: "single", kanji: "月", onyomi: "ゲツ・ガツ", kunyomi: "つき", meaning: "bulan", meaningEn: "month, moon", level: "N5",
    example: { jp: "来月国へ帰ります。", reading: "らいげつくにへかえります。", meaning: "Bulan depan pulang ke negara asal. (Next month I'll return to my country.)" } },
  { id: 17, type: "single", kanji: "火", onyomi: "カ", kunyomi: "ひ", meaning: "api", meaningEn: "fire", level: "N5",
    example: { jp: "火曜日に病院へ行きます。", reading: "かようびにびょういんへいきます。", meaning: "Pergi ke rumah sakit hari Selasa. (Go to the hospital on Tuesday.)" } },
  { id: 18, type: "single", kanji: "水", onyomi: "スイ", kunyomi: "みず", meaning: "air", meaningEn: "water", level: "N5",
    example: { jp: "水を飲みます。", reading: "みずをのみます。", meaning: "Minum air. (Drink water.)" } },
  { id: 19, type: "single", kanji: "木", onyomi: "モク・ボク", kunyomi: "き", meaning: "pohon, kayu", meaningEn: "tree, wood", level: "N5",
    example: { jp: "公園に大きい木があります。", reading: "こうえんにおおきいきがあります。", meaning: "Ada pohon besar di taman. (There's a big tree in the park.)" } },
  { id: 20, type: "single", kanji: "金", onyomi: "キン", kunyomi: "かね", meaning: "emas, uang", meaningEn: "gold, money", level: "N5",
    example: { jp: "お金がありません。", reading: "おかねがありません。", meaning: "Tidak punya uang. (I have no money.)" } },
  { id: 21, type: "single", kanji: "土", onyomi: "ド", kunyomi: "つち", meaning: "tanah", meaningEn: "earth, soil", level: "N5",
    example: { jp: "土曜日は休みです。", reading: "どようびはやすみです。", meaning: "Hari Sabtu libur. (Saturday is a day off.)" } },
  { id: 22, type: "single", kanji: "曜", onyomi: "ヨウ", kunyomi: "", meaning: "hari (dalam minggu)", meaningEn: "weekday", level: "N5",
    example: { jp: "何曜日ですか。", reading: "なんようびですか。", meaning: "Hari apa? (What day of the week is it?)" } },
  { id: 23, type: "single", kanji: "年", onyomi: "ネン", kunyomi: "とし", meaning: "tahun", meaningEn: "year", level: "N5",
    example: { jp: "今年二十歳になります。", reading: "ことしはたちになります。", meaning: "Tahun ini genap dua puluh tahun. (I'll turn 20 this year.)" } },
  { id: 24, type: "single", kanji: "時", onyomi: "ジ", kunyomi: "とき", meaning: "waktu, jam", meaningEn: "time, hour", level: "N5",
    example: { jp: "今何時ですか。", reading: "いまなんじですか。", meaning: "Sekarang jam berapa? (What time is it now?)" } },
  { id: 25, type: "single", kanji: "分", onyomi: "フン・ブン", kunyomi: "わ(ける)", meaning: "menit, bagian", meaningEn: "minute, part", level: "N5",
    example: { jp: "三十分かかります。", reading: "さんじゅっぷんかかります。", meaning: "Butuh tiga puluh menit. (It takes thirty minutes.)" } },
  { id: 26, type: "single", kanji: "半", onyomi: "ハン", kunyomi: "なか(ば)", meaning: "setengah", meaningEn: "half", level: "N5",
    example: { jp: "五時半に会います。", reading: "ごじはんにあいます。", meaning: "Bertemu jam setengah enam. (Meet at half past five.)" } },
  { id: 27, type: "single", kanji: "今", onyomi: "コン", kunyomi: "いま", meaning: "sekarang", meaningEn: "now", level: "N5",
    example: { jp: "今忙しいです。", reading: "いまいそがしいです。", meaning: "Sekarang sedang sibuk. (I'm busy now.)" } },
  { id: 28, type: "single", kanji: "何", onyomi: "カ", kunyomi: "なに・なん", meaning: "apa", meaningEn: "what", level: "N5",
    example: { jp: "これは何ですか。", reading: "これはなんですか。", meaning: "Ini apa? (What is this?)" } },
  { id: 29, type: "single", kanji: "週", onyomi: "シュウ", kunyomi: "", meaning: "minggu", meaningEn: "week", level: "N5",
    example: { jp: "来週旅行します。", reading: "らいしゅうりょこうします。", meaning: "Minggu depan bepergian. (I'll travel next week.)" } },
  { id: 30, type: "single", kanji: "先", onyomi: "セン", kunyomi: "さき", meaning: "sebelumnya, depan", meaningEn: "previous, ahead", level: "N5",
    example: { jp: "先に行ってください。", reading: "さきにいってください。", meaning: "Silakan pergi duluan. (Please go ahead.)" } },
  { id: 31, type: "single", kanji: "後", onyomi: "ゴ", kunyomi: "あと・うし(ろ)", meaning: "sesudah, belakang", meaningEn: "after, behind", level: "N5",
    example: { jp: "後で電話します。", reading: "あとででんわします。", meaning: "Nanti saya telepon. (I'll call you later.)" } },
  { id: 32, type: "single", kanji: "前", onyomi: "ゼン", kunyomi: "まえ", meaning: "sebelum, depan", meaningEn: "before, front", level: "N5",
    example: { jp: "前に会ったことがあります。", reading: "まえにあったことがあります。", meaning: "Pernah bertemu sebelumnya. (I've met before.)" } },
  { id: 33, type: "single", kanji: "午", onyomi: "ゴ", kunyomi: "", meaning: "tengah hari", meaningEn: "noon", level: "N5",
    example: { jp: "午後三時に来てください。", reading: "ごごさんじにきてください。", meaning: "Tolong datang jam tiga sore. (Please come at 3pm.)" } },
  { id: 34, type: "single", kanji: "上", onyomi: "ジョウ", kunyomi: "うえ・あ(げる)", meaning: "atas", meaningEn: "up, above", level: "N5",
    example: { jp: "机の上に本があります。", reading: "つくえのうえにほんがあります。", meaning: "Ada buku di atas meja. (There's a book on the desk.)" } },
  { id: 35, type: "single", kanji: "下", onyomi: "カ", kunyomi: "した・さ(げる)", meaning: "bawah", meaningEn: "down, below", level: "N5",
    example: { jp: "箱の下に猫がいます。", reading: "はこのしたにねこがいます。", meaning: "Ada kucing di bawah kotak. (There's a cat under the box.)" } },
  { id: 36, type: "single", kanji: "中", onyomi: "チュウ", kunyomi: "なか", meaning: "tengah, dalam", meaningEn: "middle, inside", level: "N5",
    example: { jp: "部屋の中にいます。", reading: "へやのなかにいます。", meaning: "Berada di dalam kamar. (I'm inside the room.)" } },
  { id: 37, type: "single", kanji: "外", onyomi: "ガイ", kunyomi: "そと", meaning: "luar", meaningEn: "outside", level: "N5",
    example: { jp: "外は寒いです。", reading: "そとはさむいです。", meaning: "Di luar dingin. (It's cold outside.)" } },
  { id: 38, type: "single", kanji: "右", onyomi: "ウ", kunyomi: "みぎ", meaning: "kanan", meaningEn: "right", level: "N5",
    example: { jp: "右に曲がってください。", reading: "みぎにまがってください。", meaning: "Tolong belok kanan. (Please turn right.)" } },
  { id: 39, type: "single", kanji: "左", onyomi: "サ", kunyomi: "ひだり", meaning: "kiri", meaningEn: "left", level: "N5",
    example: { jp: "左手で書きます。", reading: "ひだりてでかきます。", meaning: "Menulis dengan tangan kiri. (Write with the left hand.)" } },
  { id: 40, type: "single", kanji: "北", onyomi: "ホク", kunyomi: "きた", meaning: "utara", meaningEn: "north", level: "N5",
    example: { jp: "北の国から来ました。", reading: "きたのくにからきました。", meaning: "Datang dari negara utara. (I came from a northern country.)" } },
  { id: 41, type: "single", kanji: "南", onyomi: "ナン", kunyomi: "みなみ", meaning: "selatan", meaningEn: "south", level: "N5",
    example: { jp: "南の島へ行きたいです。", reading: "みなみのしまへいきたいです。", meaning: "Ingin pergi ke pulau selatan. (I want to go to a southern island.)" } },
  { id: 42, type: "single", kanji: "東", onyomi: "トウ", kunyomi: "ひがし", meaning: "timur", meaningEn: "east", level: "N5",
    example: { jp: "東の空が明るいです。", reading: "ひがしのそらがあかるいです。", meaning: "Langit timur terang. (The eastern sky is bright.)" } },
  { id: 43, type: "single", kanji: "西", onyomi: "セイ", kunyomi: "にし", meaning: "barat", meaningEn: "west", level: "N5",
    example: { jp: "太陽は西に沈みます。", reading: "たいようはにしにしずみます。", meaning: "Matahari terbenam di barat. (The sun sets in the west.)" } },
  { id: 44, type: "single", kanji: "間", onyomi: "カン", kunyomi: "あいだ", meaning: "jarak, antara", meaningEn: "interval, between", level: "N5",
    example: { jp: "二時間勉強しました。", reading: "にじかんべんきょうしました。", meaning: "Belajar selama dua jam. (I studied for two hours.)" } },
  { id: 45, type: "single", kanji: "人", onyomi: "ジン・ニン", kunyomi: "ひと", meaning: "orang", meaningEn: "person", level: "N5",
    example: { jp: "あの人は先生です。", reading: "あのひとはせんせいです。", meaning: "Orang itu adalah guru. (That person is a teacher.)" } },
  { id: 46, type: "single", kanji: "子", onyomi: "シ", kunyomi: "こ", meaning: "anak", meaningEn: "child", level: "N5",
    example: { jp: "子供が公園で遊んでいます。", reading: "こどもがこうえんであそんでいます。", meaning: "Anak-anak bermain di taman. (Children are playing in the park.)" } },
  { id: 47, type: "single", kanji: "女", onyomi: "ジョ", kunyomi: "おんな", meaning: "wanita", meaningEn: "woman", level: "N5",
    example: { jp: "あの女の人は親切です。", reading: "あのおんなのひとはしんせつです。", meaning: "Wanita itu baik hati. (That woman is kind.)" } },
  { id: 48, type: "single", kanji: "男", onyomi: "ダン", kunyomi: "おとこ", meaning: "pria", meaningEn: "man", level: "N5",
    example: { jp: "その男の子は元気です。", reading: "そのおとこのこはげんきです。", meaning: "Anak laki-laki itu sehat. (That boy is energetic.)" } },
  { id: 49, type: "single", kanji: "私", onyomi: "シ", kunyomi: "わたし", meaning: "saya", meaningEn: "I, me", level: "N5",
    example: { jp: "私は学生です。", reading: "わたしはがくせいです。", meaning: "Saya seorang murid. (I am a student.)" } },
  { id: 50, type: "single", kanji: "友", onyomi: "ユウ", kunyomi: "とも", meaning: "teman", meaningEn: "friend", level: "N5",
    example: { jp: "友達と遊びます。", reading: "ともだちとあそびます。", meaning: "Bermain dengan teman. (Play with friends.)" } },
  { id: 51, type: "single", kanji: "母", onyomi: "ボ", kunyomi: "はは", meaning: "ibu", meaningEn: "mother", level: "N5",
    example: { jp: "母は料理が上手です。", reading: "はははりょうりがじょうずです。", meaning: "Ibu pandai memasak. (Mother is good at cooking.)" } },
  { id: 52, type: "single", kanji: "父", onyomi: "フ", kunyomi: "ちち", meaning: "ayah", meaningEn: "father", level: "N5",
    example: { jp: "父は会社員です。", reading: "ちちはかいしゃいんです。", meaning: "Ayah seorang pegawai perusahaan. (Father is a company employee.)" } },
  { id: 53, type: "single", kanji: "兄", onyomi: "ケイ", kunyomi: "あに", meaning: "kakak laki-laki", meaningEn: "older brother", level: "N5",
    example: { jp: "兄は大学生です。", reading: "あにはだいがくせいです。", meaning: "Kakak laki-laki adalah mahasiswa. (My older brother is a university student.)" } },
  { id: 54, type: "single", kanji: "姉", onyomi: "シ", kunyomi: "あね", meaning: "kakak perempuan", meaningEn: "older sister", level: "N5",
    example: { jp: "姉は医者です。", reading: "あねはいしゃです。", meaning: "Kakak perempuan adalah dokter. (My older sister is a doctor.)" } },
  { id: 55, type: "single", kanji: "弟", onyomi: "ダイ", kunyomi: "おとうと", meaning: "adik laki-laki", meaningEn: "younger brother", level: "N5",
    example: { jp: "弟はまだ小学生です。", reading: "おとうとはまだしょうがくせいです。", meaning: "Adik laki-laki masih murid SD. (My younger brother is still an elementary student.)" } },
  { id: 56, type: "single", kanji: "妹", onyomi: "マイ", kunyomi: "いもうと", meaning: "adik perempuan", meaningEn: "younger sister", level: "N5",
    example: { jp: "妹は歌が好きです。", reading: "いもうとはうたがすきです。", meaning: "Adik perempuan suka menyanyi. (My younger sister likes singing.)" } },
  { id: 57, type: "single", kanji: "名", onyomi: "メイ", kunyomi: "な", meaning: "nama", meaningEn: "name", level: "N5",
    example: { jp: "お名前は何ですか。", reading: "おなまえはなんですか。", meaning: "Siapa nama Anda? (What is your name?)" } },
  { id: 58, type: "single", kanji: "学", onyomi: "ガク", kunyomi: "まな(ぶ)", meaning: "belajar", meaningEn: "study", level: "N5",
    example: { jp: "日本語を学びます。", reading: "にほんごをまなびます。", meaning: "Belajar bahasa Jepang. (Study the Japanese language.)" } },
  { id: 59, type: "single", kanji: "校", onyomi: "コウ", kunyomi: "", meaning: "sekolah", meaningEn: "school", level: "N5",
    example: { jp: "学校まで歩きます。", reading: "がっこうまであるきます。", meaning: "Berjalan kaki ke sekolah. (Walk to school.)" } },
  { id: 60, type: "single", kanji: "生", onyomi: "セイ", kunyomi: "い(きる)", meaning: "hidup, lahir", meaningEn: "life, birth", level: "N5",
    example: { jp: "一年生になりました。", reading: "いちねんせいになりました。", meaning: "Menjadi murid kelas satu. (Became a first-year student.)" } },
  { id: 61, type: "single", kanji: "語", onyomi: "ゴ", kunyomi: "かた(る)", meaning: "bahasa", meaningEn: "language", level: "N5",
    example: { jp: "英語を話せますか。", reading: "えいごをはなせますか。", meaning: "Bisakah Anda berbicara bahasa Inggris? (Can you speak English?)" } },
  { id: 62, type: "single", kanji: "文", onyomi: "ブン", kunyomi: "ふみ", meaning: "kalimat, tulisan", meaningEn: "sentence, writing", level: "N5",
    example: { jp: "この文を読んでください。", reading: "このぶんをよんでください。", meaning: "Tolong baca kalimat ini. (Please read this sentence.)" } },
  { id: 63, type: "single", kanji: "字", onyomi: "ジ", kunyomi: "", meaning: "huruf", meaningEn: "character", level: "N5",
    example: { jp: "漢字を勉強しています。", reading: "かんじをべんきょうしています。", meaning: "Sedang belajar kanji. (I'm studying kanji characters.)" } },
  { id: 64, type: "single", kanji: "本", onyomi: "ホン", kunyomi: "もと", meaning: "buku, asal", meaningEn: "book, origin", level: "N5",
    example: { jp: "図書館で本を借ります。", reading: "としょかんでほんをかります。", meaning: "Meminjam buku di perpustakaan. (Borrow a book at the library.)" } },
  { id: 65, type: "single", kanji: "山", onyomi: "サン", kunyomi: "やま", meaning: "gunung", meaningEn: "mountain", level: "N5",
    example: { jp: "富士山に登りたいです。", reading: "ふじさんにのぼりたいです。", meaning: "Ingin mendaki Gunung Fuji. (I want to climb Mt. Fuji.)" } },
  { id: 66, type: "single", kanji: "川", onyomi: "セン", kunyomi: "かわ", meaning: "sungai", meaningEn: "river", level: "N5",
    example: { jp: "川で泳ぎました。", reading: "かわでおよぎました。", meaning: "Berenang di sungai. (Swam in the river.)" } },
  { id: 67, type: "single", kanji: "田", onyomi: "デン", kunyomi: "た", meaning: "sawah", meaningEn: "rice field", level: "N5",
    example: { jp: "田んぼで働きます。", reading: "たんぼではたらきます。", meaning: "Bekerja di sawah. (Work in the rice field.)" } },
  { id: 68, type: "single", kanji: "天", onyomi: "テン", kunyomi: "あま", meaning: "langit", meaningEn: "heaven, sky", level: "N5",
    example: { jp: "明日の天気はどうですか。", reading: "あしたのてんきはどうですか。", meaning: "Bagaimana cuaca besok? (How's the weather tomorrow?)" } },
  { id: 69, type: "single", kanji: "空", onyomi: "クウ", kunyomi: "そら", meaning: "langit, kosong", meaningEn: "sky, empty", level: "N5",
    example: { jp: "空が青いです。", reading: "そらがあおいです。", meaning: "Langit berwarna biru. (The sky is blue.)" } },
  { id: 70, type: "single", kanji: "気", onyomi: "キ", kunyomi: "", meaning: "semangat, udara", meaningEn: "spirit, energy", level: "N5",
    example: { jp: "元気ですか。", reading: "げんきですか。", meaning: "Apa kabar? (How are you?)" } },
  { id: 71, type: "single", kanji: "花", onyomi: "カ", kunyomi: "はな", meaning: "bunga", meaningEn: "flower", level: "N5",
    example: { jp: "花がきれいに咲いています。", reading: "はながきれいにさいています。", meaning: "Bunga mekar dengan indah. (The flowers are blooming beautifully.)" } },
  { id: 72, type: "single", kanji: "石", onyomi: "セキ", kunyomi: "いし", meaning: "batu", meaningEn: "stone", level: "N5",
    example: { jp: "川で石を拾いました。", reading: "かわでいしをひろいました。", meaning: "Memungut batu di sungai. (Picked up a stone at the river.)" } },
  { id: 73, type: "single", kanji: "海", onyomi: "カイ", kunyomi: "うみ", meaning: "laut", meaningEn: "sea", level: "N5",
    example: { jp: "夏は海へ行きます。", reading: "なつはうみへいきます。", meaning: "Musim panas pergi ke laut. (In summer, I go to the sea.)" } },
  { id: 74, type: "single", kanji: "目", onyomi: "モク", kunyomi: "め", meaning: "mata", meaningEn: "eye", level: "N5",
    example: { jp: "目が痛いです。", reading: "めがいたいです。", meaning: "Mata saya sakit. (My eyes hurt.)" } },
  { id: 75, type: "single", kanji: "耳", onyomi: "ジ", kunyomi: "みみ", meaning: "telinga", meaningEn: "ear", level: "N5",
    example: { jp: "耳が大きいです。", reading: "みみがおおきいです。", meaning: "Telinganya besar. (Its ears are big.)" } },
  { id: 76, type: "single", kanji: "口", onyomi: "コウ", kunyomi: "くち", meaning: "mulut", meaningEn: "mouth", level: "N5",
    example: { jp: "口を大きく開けてください。", reading: "くちをおおきくあけてください。", meaning: "Tolong buka mulut lebar-lebar. (Please open your mouth wide.)" } },
  { id: 77, type: "single", kanji: "手", onyomi: "シュ", kunyomi: "て", meaning: "tangan", meaningEn: "hand", level: "N5",
    example: { jp: "手を洗います。", reading: "てをあらいます。", meaning: "Mencuci tangan. (Wash hands.)" } },
  { id: 78, type: "single", kanji: "足", onyomi: "ソク", kunyomi: "あし", meaning: "kaki", meaningEn: "foot, leg", level: "N5",
    example: { jp: "足が痛いです。", reading: "あしがいたいです。", meaning: "Kaki saya sakit. (My leg hurts.)" } },
  { id: 79, type: "single", kanji: "行", onyomi: "コウ", kunyomi: "い(く)", meaning: "pergi", meaningEn: "go", level: "N5",
    example: { jp: "明日学校に行きます。", reading: "あしたがっこうにいきます。", meaning: "Besok pergi ke sekolah. (Tomorrow I'll go to school.)" } },
  { id: 80, type: "single", kanji: "来", onyomi: "ライ", kunyomi: "く(る)", meaning: "datang", meaningEn: "come", level: "N5",
    example: { jp: "友達が家に来ます。", reading: "ともだちがいえにきます。", meaning: "Teman datang ke rumah. (A friend comes to my house.)" } },
  { id: 81, type: "single", kanji: "帰", onyomi: "キ", kunyomi: "かえ(る)", meaning: "pulang", meaningEn: "return", level: "N5",
    example: { jp: "七時に家へ帰ります。", reading: "しちじにいえへかえります。", meaning: "Pulang ke rumah jam tujuh. (Return home at seven.)" } },
  { id: 82, type: "single", kanji: "見", onyomi: "ケン", kunyomi: "み(る)", meaning: "melihat", meaningEn: "see", level: "N5",
    example: { jp: "テレビを見ます。", reading: "てれびをみます。", meaning: "Menonton televisi. (Watch television.)" } },
  { id: 83, type: "single", kanji: "聞", onyomi: "ブン", kunyomi: "き(く)", meaning: "mendengar, bertanya", meaningEn: "hear, ask", level: "N5",
    example: { jp: "音楽を聞きます。", reading: "おんがくをききます。", meaning: "Mendengarkan musik. (Listen to music.)" } },
  { id: 84, type: "single", kanji: "話", onyomi: "ワ", kunyomi: "はな(す)", meaning: "berbicara", meaningEn: "speak", level: "N5",
    example: { jp: "電話で話します。", reading: "でんわではなします。", meaning: "Berbicara lewat telepon. (Talk on the phone.)" } },
  { id: 85, type: "single", kanji: "読", onyomi: "ドク", kunyomi: "よ(む)", meaning: "membaca", meaningEn: "read", level: "N5",
    example: { jp: "新聞を読みます。", reading: "しんぶんをよみます。", meaning: "Membaca koran. (Read the newspaper.)" } },
  { id: 86, type: "single", kanji: "書", onyomi: "ショ", kunyomi: "か(く)", meaning: "menulis", meaningEn: "write", level: "N5",
    example: { jp: "手紙を書きます。", reading: "てがみをかきます。", meaning: "Menulis surat. (Write a letter.)" } },
  { id: 87, type: "single", kanji: "買", onyomi: "バイ", kunyomi: "か(う)", meaning: "membeli", meaningEn: "buy", level: "N5",
    example: { jp: "果物を買います。", reading: "くだものをかいます。", meaning: "Membeli buah. (Buy fruit.)" } },
  { id: 88, type: "single", kanji: "食", onyomi: "ショク", kunyomi: "た(べる)", meaning: "makan, makanan", meaningEn: "eat, food", level: "N5",
    example: { jp: "朝ご飯を食べます。", reading: "あさごはんをたべます。", meaning: "Makan sarapan. (Eat breakfast.)" } },
  { id: 89, type: "single", kanji: "飲", onyomi: "イン", kunyomi: "の(む)", meaning: "minum", meaningEn: "drink", level: "N5",
    example: { jp: "コーヒーを飲みます。", reading: "こーひーをのみます。", meaning: "Minum kopi. (Drink coffee.)" } },
  { id: 90, type: "single", kanji: "立", onyomi: "リツ", kunyomi: "た(つ)", meaning: "berdiri", meaningEn: "stand", level: "N5",
    example: { jp: "ここに立ってください。", reading: "ここにたってください。", meaning: "Tolong berdiri di sini. (Please stand here.)" } },
  { id: 91, type: "single", kanji: "休", onyomi: "キュウ", kunyomi: "やす(む)", meaning: "istirahat", meaningEn: "rest", level: "N5",
    example: { jp: "今日は仕事を休みます。", reading: "きょうはしごとをやすみます。", meaning: "Hari ini libur kerja. (I'll take a day off work today.)" } },
  { id: 92, type: "single", kanji: "入", onyomi: "ニュウ", kunyomi: "はい(る)", meaning: "masuk", meaningEn: "enter", level: "N5",
    example: { jp: "部屋に入ります。", reading: "へやにはいります。", meaning: "Masuk ke kamar. (Enter the room.)" } },
  { id: 93, type: "single", kanji: "出", onyomi: "シュツ", kunyomi: "で(る)", meaning: "keluar", meaningEn: "exit", level: "N5",
    example: { jp: "家を出ます。", reading: "いえをでます。", meaning: "Keluar dari rumah. (Leave the house.)" } },
  { id: 94, type: "single", kanji: "会", onyomi: "カイ", kunyomi: "あ(う)", meaning: "bertemu", meaningEn: "meet", level: "N5",
    example: { jp: "友達に会います。", reading: "ともだちにあいます。", meaning: "Bertemu teman. (Meet a friend.)" } },
  { id: 95, type: "single", kanji: "大", onyomi: "ダイ", kunyomi: "おお(きい)", meaning: "besar", meaningEn: "big", level: "N5",
    example: { jp: "これは大きい犬です。", reading: "これはおおきいいぬです。", meaning: "Ini anjing besar. (This is a big dog.)" } },
  { id: 96, type: "single", kanji: "小", onyomi: "ショウ", kunyomi: "ちい(さい)", meaning: "kecil", meaningEn: "small", level: "N5",
    example: { jp: "小さい部屋に住んでいます。", reading: "ちいさいへやにすんでいます。", meaning: "Tinggal di kamar kecil. (I live in a small room.)" } },
  { id: 97, type: "single", kanji: "高", onyomi: "コウ", kunyomi: "たか(い)", meaning: "tinggi, mahal", meaningEn: "high, expensive", level: "N5",
    example: { jp: "この山は高いです。", reading: "このやまはたかいです。", meaning: "Gunung ini tinggi. (This mountain is high.)" } },
  { id: 98, type: "single", kanji: "安", onyomi: "アン", kunyomi: "やす(い)", meaning: "murah, aman", meaningEn: "cheap, safe", level: "N5",
    example: { jp: "この店は安いです。", reading: "このみせはやすいです。", meaning: "Toko ini murah. (This shop is cheap.)" } },
  { id: 99, type: "single", kanji: "新", onyomi: "シン", kunyomi: "あたら(しい)", meaning: "baru", meaningEn: "new", level: "N5",
    example: { jp: "新しい車を買いました。", reading: "あたらしいくるまをかいました。", meaning: "Membeli mobil baru. (Bought a new car.)" } },
  { id: 100, type: "single", kanji: "古", onyomi: "コ", kunyomi: "ふる(い)", meaning: "lama, tua", meaningEn: "old", level: "N5",
    example: { jp: "古い家に住んでいます。", reading: "ふるいいえにすんでいます。", meaning: "Tinggal di rumah tua. (I live in an old house.)" } },
  { id: 101, type: "single", kanji: "長", onyomi: "チョウ", kunyomi: "なが(い)", meaning: "panjang", meaningEn: "long", level: "N5",
    example: { jp: "髪が長いです。", reading: "かみがながいです。", meaning: "Rambutnya panjang. (Her hair is long.)" } },
  { id: 102, type: "single", kanji: "多", onyomi: "タ", kunyomi: "おお(い)", meaning: "banyak", meaningEn: "many", level: "N5",
    example: { jp: "人が多いです。", reading: "ひとがおおいです。", meaning: "Orangnya banyak. (There are many people.)" } },
  { id: 103, type: "single", kanji: "少", onyomi: "ショウ", kunyomi: "すこ(し)", meaning: "sedikit", meaningEn: "few, little", level: "N5",
    example: { jp: "お金が少ないです。", reading: "おかねがすくないです。", meaning: "Uangnya sedikit. (I have little money.)" } },

  { id: 104, type: "single", kanji: "早", onyomi: "ソウ", kunyomi: "はや(い)", meaning: "cepat, awal", meaningEn: "early, fast", level: "N4",
    example: { jp: "朝早く起きます。", reading: "あさはやくおきます。", meaning: "Bangun pagi-pagi sekali. (Wake up early in the morning.)" } },
  { id: 105, type: "single", kanji: "車", onyomi: "シャ", kunyomi: "くるま", meaning: "mobil", meaningEn: "car", level: "N4",
    example: { jp: "車で会社へ行きます。", reading: "くるまでかいしゃへいきます。", meaning: "Pergi ke kantor naik mobil. (Go to the office by car.)" } },
  { id: 106, type: "single", kanji: "電", onyomi: "デン", kunyomi: "", meaning: "listrik", meaningEn: "electricity", level: "N4",
    example: { jp: "電気を消してください。", reading: "でんきをけしてください。", meaning: "Tolong matikan listrik. (Please turn off the electricity.)" } },
  { id: 107, type: "single", kanji: "駅", onyomi: "エキ", kunyomi: "", meaning: "stasiun", meaningEn: "station", level: "N4",
    example: { jp: "駅まで歩きます。", reading: "えきまであるきます。", meaning: "Berjalan kaki ke stasiun. (Walk to the station.)" } },
  { id: 108, type: "single", kanji: "店", onyomi: "テン", kunyomi: "みせ", meaning: "toko", meaningEn: "shop", level: "N4",
    example: { jp: "この店で買い物をします。", reading: "このみせでかいものをします。", meaning: "Berbelanja di toko ini. (Shop at this store.)" } },
  { id: 109, type: "single", kanji: "家", onyomi: "カ", kunyomi: "いえ・うち", meaning: "rumah", meaningEn: "house", level: "N4",
    example: { jp: "家族と家にいます。", reading: "かぞくといえにいます。", meaning: "Berada di rumah bersama keluarga. (I'm at home with my family.)" } },
  { id: 110, type: "single", kanji: "国", onyomi: "コク", kunyomi: "くに", meaning: "negara", meaningEn: "country", level: "N4",
    example: { jp: "どこの国から来ましたか。", reading: "どこのくにからきましたか。", meaning: "Anda berasal dari negara mana? (Which country are you from?)" } },
  { id: 111, type: "single", kanji: "白", onyomi: "ハク", kunyomi: "しろ", meaning: "putih", meaningEn: "white", level: "N4",
    example: { jp: "白いシャツを着ています。", reading: "しろいしゃつをきています。", meaning: "Memakai kemeja putih. (Wearing a white shirt.)" } },
  { id: 112, type: "single", kanji: "黒", onyomi: "コク", kunyomi: "くろ", meaning: "hitam", meaningEn: "black", level: "N4",
    example: { jp: "黒い猫がいます。", reading: "くろいねこがいます。", meaning: "Ada kucing hitam. (There's a black cat.)" } },
  { id: 113, type: "single", kanji: "赤", onyomi: "セキ", kunyomi: "あか", meaning: "merah", meaningEn: "red", level: "N4",
    example: { jp: "赤いりんごを買いました。", reading: "あかいりんごをかいました。", meaning: "Membeli apel merah. (Bought a red apple.)" } },
  { id: 114, type: "single", kanji: "青", onyomi: "セイ", kunyomi: "あお", meaning: "biru", meaningEn: "blue", level: "N4",
    example: { jp: "青信号で渡ります。", reading: "あおしんごうでわたります。", meaning: "Menyeberang saat lampu hijau. (Cross at the green light.)" } },
  { id: 115, type: "single", kanji: "元", onyomi: "ゲン", kunyomi: "もと", meaning: "asal", meaningEn: "origin", level: "N4",
    example: { jp: "元気に働いています。", reading: "げんきにはたらいています。", meaning: "Bekerja dengan penuh semangat. (Working energetically.)" } },
  { id: 116, type: "single", kanji: "事", onyomi: "ジ", kunyomi: "こと", meaning: "hal, perkara", meaningEn: "matter, thing", level: "N4",
    example: { jp: "大事な用事があります。", reading: "だいじなようじがあります。", meaning: "Ada urusan penting. (I have an important matter.)" } },
  { id: 117, type: "single", kanji: "物", onyomi: "ブツ", kunyomi: "もの", meaning: "benda", meaningEn: "thing, object", level: "N4",
    example: { jp: "この荷物は重いです。", reading: "このにもつはおもいです。", meaning: "Barang ini berat. (This luggage is heavy.)" } },
  { id: 118, type: "single", kanji: "所", onyomi: "ショ", kunyomi: "ところ", meaning: "tempat", meaningEn: "place", level: "N4",
    example: { jp: "住所を教えてください。", reading: "じゅうしょをおしえてください。", meaning: "Tolong beri tahu alamat Anda. (Please tell me your address.)" } },
  { id: 119, type: "single", kanji: "道", onyomi: "ドウ", kunyomi: "みち", meaning: "jalan", meaningEn: "road, way", level: "N4",
    example: { jp: "この道をまっすぐ行ってください。", reading: "このみちをまっすぐいってください。", meaning: "Tolong jalan lurus di jalan ini. (Please go straight on this road.)" } },
  { id: 120, type: "single", kanji: "町", onyomi: "チョウ", kunyomi: "まち", meaning: "kota kecil", meaningEn: "town", level: "N4",
    example: { jp: "静かな町に住んでいます。", reading: "しずかなまちにすんでいます。", meaning: "Tinggal di kota kecil yang tenang. (I live in a quiet town.)" } },
  { id: 121, type: "single", kanji: "村", onyomi: "ソン", kunyomi: "むら", meaning: "desa", meaningEn: "village", level: "N4",
    example: { jp: "小さい村で生まれました。", reading: "ちいさいむらでうまれました。", meaning: "Lahir di desa kecil. (Born in a small village.)" } },
  { id: 122, type: "single", kanji: "市", onyomi: "シ", kunyomi: "いち", meaning: "kota", meaningEn: "city", level: "N4",
    example: { jp: "市役所に行きます。", reading: "しやくしょにいきます。", meaning: "Pergi ke balai kota. (Go to city hall.)" } },
  { id: 123, type: "single", kanji: "区", onyomi: "ク", kunyomi: "", meaning: "distrik", meaningEn: "ward, district", level: "N4",
    example: { jp: "この区に住んでいます。", reading: "このくにすんでいます。", meaning: "Tinggal di distrik ini. (I live in this ward.)" } },
  { id: 124, type: "single", kanji: "世", onyomi: "セ", kunyomi: "よ", meaning: "dunia, generasi", meaningEn: "world, generation", level: "N4",
    example: { jp: "世の中は便利になりました。", reading: "よのなかはべんりになりました。", meaning: "Dunia menjadi lebih praktis. (The world has become more convenient.)" } },
  { id: 125, type: "single", kanji: "界", onyomi: "カイ", kunyomi: "", meaning: "dunia, batas", meaningEn: "world, boundary", level: "N4",
    example: { jp: "世界を旅行したいです。", reading: "せかいをりょこうしたいです。", meaning: "Ingin bepergian keliling dunia. (I want to travel the world.)" } },
  { id: 126, type: "single", kanji: "全", onyomi: "ゼン", kunyomi: "まった(く)", meaning: "semua", meaningEn: "all, whole", level: "N4",
    example: { jp: "全部食べました。", reading: "ぜんぶたべました。", meaning: "Makan semuanya. (Ate everything.)" } },
  { id: 127, type: "single", kanji: "部", onyomi: "ブ", kunyomi: "", meaning: "bagian", meaningEn: "part, department", level: "N4",
    example: { jp: "一部を直してください。", reading: "いちぶをなおしてください。", meaning: "Tolong perbaiki sebagiannya. (Please fix a part of it.)" } },
  { id: 128, type: "single", kanji: "屋", onyomi: "オク", kunyomi: "や", meaning: "toko, atap", meaningEn: "shop, roof", level: "N4",
    example: { jp: "本屋で本を買います。", reading: "ほんやでほんをかいます。", meaning: "Membeli buku di toko buku. (Buy a book at the bookstore.)" } },
  { id: 129, type: "single", kanji: "品", onyomi: "ヒン", kunyomi: "しな", meaning: "barang", meaningEn: "goods", level: "N4",
    example: { jp: "この品物は高いです。", reading: "このしなものはたかいです。", meaning: "Barang ini mahal. (This item is expensive.)" } },
  { id: 130, type: "single", kanji: "産", onyomi: "サン", kunyomi: "う(む)", meaning: "produksi, lahir", meaningEn: "produce, give birth", level: "N4",
    example: { jp: "京都の名産品です。", reading: "きょうとのめいさんひんです。", meaning: "Produk khas Kyoto. (A specialty product of Kyoto.)" } },
  { id: 131, type: "single", kanji: "業", onyomi: "ギョウ", kunyomi: "", meaning: "usaha, pekerjaan", meaningEn: "business, occupation", level: "N4",
    example: { jp: "授業に出ます。", reading: "じゅぎょうにでます。", meaning: "Mengikuti kelas. (Attend class.)" } },
  { id: 132, type: "single", kanji: "仕", onyomi: "シ", kunyomi: "つか(える)", meaning: "melayani", meaningEn: "serve", level: "N4",
    example: { jp: "仕事が忙しいです。", reading: "しごとがいそがしいです。", meaning: "Pekerjaan sedang sibuk. (Work is busy.)" } },
  { id: 133, type: "single", kanji: "使", onyomi: "シ", kunyomi: "つか(う)", meaning: "menggunakan", meaningEn: "use", level: "N4",
    example: { jp: "このペンを使ってもいいですか。", reading: "このぺんをつかってもいいですか。", meaning: "Bolehkah saya pakai pena ini? (May I use this pen?)" } },
  { id: 134, type: "single", kanji: "働", onyomi: "ドウ", kunyomi: "はたら(く)", meaning: "bekerja", meaningEn: "to work", level: "N4",
    example: { jp: "会社で働いています。", reading: "かいしゃではたらいています。", meaning: "Bekerja di perusahaan. (Working at a company.)" } },
  { id: 135, type: "single", kanji: "教", onyomi: "キョウ", kunyomi: "おし(える)", meaning: "mengajar", meaningEn: "teach", level: "N4",
    example: { jp: "日本語を教えています。", reading: "にほんごをおしえています。", meaning: "Mengajar bahasa Jepang. (Teaching Japanese.)" } },
  { id: 136, type: "single", kanji: "室", onyomi: "シツ", kunyomi: "むろ", meaning: "kamar", meaningEn: "room", level: "N4",
    example: { jp: "教室で勉強します。", reading: "きょうしつでべんきょうします。", meaning: "Belajar di ruang kelas. (Study in the classroom.)" } },
  { id: 137, type: "single", kanji: "図", onyomi: "ズ", kunyomi: "はか(る)", meaning: "diagram, rencana", meaningEn: "diagram, plan", level: "N4",
    example: { jp: "図書館で本を読みます。", reading: "としょかんでほんをよみます。", meaning: "Membaca buku di perpustakaan. (Read a book at the library.)" } },
  { id: 138, type: "single", kanji: "館", onyomi: "カン", kunyomi: "", meaning: "gedung", meaningEn: "hall, building", level: "N4",
    example: { jp: "美術館へ行きました。", reading: "びじゅつかんへいきました。", meaning: "Pergi ke museum seni. (Went to the art museum.)" } },
  { id: 139, type: "single", kanji: "病", onyomi: "ビョウ", kunyomi: "やまい", meaning: "sakit", meaningEn: "illness", level: "N4",
    example: { jp: "病気で休みました。", reading: "びょうきでやすみました。", meaning: "Absen karena sakit. (Absent due to illness.)" } },
  { id: 140, type: "single", kanji: "院", onyomi: "イン", kunyomi: "", meaning: "institusi", meaningEn: "institution", level: "N4",
    example: { jp: "病院で働いています。", reading: "びょういんではたらいています。", meaning: "Bekerja di rumah sakit. (Working at a hospital.)" } },
  { id: 141, type: "single", kanji: "医", onyomi: "イ", kunyomi: "", meaning: "kedokteran, dokter", meaningEn: "medicine, doctor", level: "N4",
    example: { jp: "医者になりたいです。", reading: "いしゃになりたいです。", meaning: "Ingin menjadi dokter. (I want to become a doctor.)" } },
  { id: 142, type: "single", kanji: "者", onyomi: "シャ", kunyomi: "もの", meaning: "orang", meaningEn: "person", level: "N4",
    example: { jp: "あの若者は元気です。", reading: "あのわかものはげんきです。", meaning: "Anak muda itu bersemangat. (That young person is energetic.)" } },
  { id: 143, type: "single", kanji: "動", onyomi: "ドウ", kunyomi: "うご(く)", meaning: "bergerak", meaningEn: "move", level: "N4",
    example: { jp: "車が動きません。", reading: "くるまがうごきません。", meaning: "Mobilnya tidak bergerak. (The car won't move.)" } },
  { id: 144, type: "single", kanji: "作", onyomi: "サク", kunyomi: "つく(る)", meaning: "membuat", meaningEn: "make", level: "N4",
    example: { jp: "料理を作ります。", reading: "りょうりをつくります。", meaning: "Memasak makanan. (Make/cook food.)" } },
  { id: 145, type: "single", kanji: "始", onyomi: "シ", kunyomi: "はじ(める)", meaning: "memulai", meaningEn: "begin", level: "N4",
    example: { jp: "授業が始まります。", reading: "じゅぎょうがはじまります。", meaning: "Kelas akan dimulai. (Class is starting.)" } },
  { id: 146, type: "single", kanji: "終", onyomi: "シュウ", kunyomi: "お(わる)", meaning: "mengakhiri", meaningEn: "end", level: "N4",
    example: { jp: "仕事が終わりました。", reading: "しごとがおわりました。", meaning: "Pekerjaan sudah selesai. (Work has ended.)" } },
  { id: 147, type: "single", kanji: "開", onyomi: "カイ", kunyomi: "ひら(く)", meaning: "membuka", meaningEn: "open", level: "N4",
    example: { jp: "ドアを開けてください。", reading: "どあをあけてください。", meaning: "Tolong buka pintunya. (Please open the door.)" } },
  { id: 148, type: "single", kanji: "閉", onyomi: "ヘイ", kunyomi: "し(める)", meaning: "menutup", meaningEn: "close", level: "N4",
    example: { jp: "店は九時に閉まります。", reading: "みせはくじにしまります。", meaning: "Toko tutup jam sembilan. (The shop closes at nine.)" } },
  { id: 149, type: "single", kanji: "走", onyomi: "ソウ", kunyomi: "はし(る)", meaning: "berlari", meaningEn: "run", level: "N4",
    example: { jp: "毎朝走ります。", reading: "まいあさはしります。", meaning: "Berlari setiap pagi. (Run every morning.)" } },
  { id: 150, type: "single", kanji: "歩", onyomi: "ホ", kunyomi: "ある(く)", meaning: "berjalan", meaningEn: "walk", level: "N4",
    example: { jp: "公園を歩きます。", reading: "こうえんをあるきます。", meaning: "Berjalan-jalan di taman. (Walk in the park.)" } },
  { id: 151, type: "single", kanji: "止", onyomi: "シ", kunyomi: "と(まる)", meaning: "berhenti", meaningEn: "stop", level: "N4",
    example: { jp: "ここで止まってください。", reading: "ここでとまってください。", meaning: "Tolong berhenti di sini. (Please stop here.)" } },
  { id: 152, type: "single", kanji: "待", onyomi: "タイ", kunyomi: "ま(つ)", meaning: "menunggu", meaningEn: "wait", level: "N4",
    example: { jp: "バスを待っています。", reading: "ばすをまっています。", meaning: "Sedang menunggu bus. (Waiting for the bus.)" } },
  { id: 153, type: "single", kanji: "貸", onyomi: "タイ", kunyomi: "か(す)", meaning: "meminjamkan", meaningEn: "lend", level: "N4",
    example: { jp: "傘を貸してください。", reading: "かさをかしてください。", meaning: "Tolong pinjamkan payung. (Please lend me an umbrella.)" } },
  { id: 154, type: "single", kanji: "借", onyomi: "シャク", kunyomi: "か(りる)", meaning: "meminjam", meaningEn: "borrow", level: "N4",
    example: { jp: "友達にお金を借りました。", reading: "ともだちにおかねをかりました。", meaning: "Meminjam uang dari teman. (Borrowed money from a friend.)" } },
  { id: 155, type: "single", kanji: "送", onyomi: "ソウ", kunyomi: "おく(る)", meaning: "mengirim", meaningEn: "send", level: "N4",
    example: { jp: "手紙を送ります。", reading: "てがみをおくります。", meaning: "Mengirim surat. (Send a letter.)" } },
  { id: 156, type: "single", kanji: "受", onyomi: "ジュ", kunyomi: "う(ける)", meaning: "menerima", meaningEn: "receive", level: "N4",
    example: { jp: "試験を受けます。", reading: "しけんをうけます。", meaning: "Mengikuti ujian. (Take an exam.)" } },
  { id: 157, type: "single", kanji: "持", onyomi: "ジ", kunyomi: "も(つ)", meaning: "memegang, punya", meaningEn: "hold, have", level: "N4",
    example: { jp: "かばんを持っています。", reading: "かばんをもっています。", meaning: "Membawa tas. (Holding a bag.)" } },
  { id: 158, type: "single", kanji: "忘", onyomi: "ボウ", kunyomi: "わす(れる)", meaning: "melupakan", meaningEn: "forget", level: "N4",
    example: { jp: "傘を忘れました。", reading: "かさをわすれました。", meaning: "Lupa membawa payung. (Forgot my umbrella.)" } },
  { id: 159, type: "single", kanji: "覚", onyomi: "カク", kunyomi: "おぼ(える)", meaning: "mengingat", meaningEn: "remember", level: "N4",
    example: { jp: "単語を覚えます。", reading: "たんごをおぼえます。", meaning: "Menghafal kosakata. (Memorize vocabulary.)" } },
  { id: 160, type: "single", kanji: "考", onyomi: "コウ", kunyomi: "かんが(える)", meaning: "berpikir", meaningEn: "think", level: "N4",
    example: { jp: "よく考えてください。", reading: "よくかんがえてください。", meaning: "Tolong pikirkan baik-baik. (Please think carefully.)" } },
  { id: 161, type: "single", kanji: "知", onyomi: "チ", kunyomi: "し(る)", meaning: "mengetahui", meaningEn: "know", level: "N4",
    example: { jp: "その話を知っています。", reading: "そのはなしをしっています。", meaning: "Mengetahui cerita itu. (I know that story.)" } },
  { id: 162, type: "single", kanji: "思", onyomi: "シ", kunyomi: "おも(う)", meaning: "berpikir, merasa", meaningEn: "think, feel", level: "N4",
    example: { jp: "そう思います。", reading: "そうおもいます。", meaning: "Saya pikir begitu. (I think so.)" } },
  { id: 163, type: "single", kanji: "答", onyomi: "トウ", kunyomi: "こた(える)", meaning: "menjawab", meaningEn: "answer", level: "N4",
    example: { jp: "質問に答えます。", reading: "しつもんにこたえます。", meaning: "Menjawab pertanyaan. (Answer the question.)" } },
  { id: 164, type: "single", kanji: "問", onyomi: "モン", kunyomi: "と(う)", meaning: "bertanya", meaningEn: "ask, question", level: "N4",
    example: { jp: "問題が難しいです。", reading: "もんだいがむずかしいです。", meaning: "Soalnya sulit. (The question is difficult.)" } },
  { id: 165, type: "single", kanji: "質", onyomi: "シツ", kunyomi: "", meaning: "kualitas, pertanyaan", meaningEn: "quality, question", level: "N4",
    example: { jp: "質問がありますか。", reading: "しつもんがありますか。", meaning: "Ada pertanyaan? (Do you have any questions?)" } },
  { id: 166, type: "single", kanji: "集", onyomi: "シュウ", kunyomi: "あつ(まる)", meaning: "berkumpul", meaningEn: "gather", level: "N4",
    example: { jp: "友達が公園に集まります。", reading: "ともだちがこうえんにあつまります。", meaning: "Teman-teman berkumpul di taman. (Friends gather at the park.)" } },
  { id: 167, type: "single", kanji: "決", onyomi: "ケツ", kunyomi: "き(める)", meaning: "memutuskan", meaningEn: "decide", level: "N4",
    example: { jp: "予定を決めました。", reading: "よていをきめました。", meaning: "Sudah memutuskan rencana. (Decided on the plan.)" } },
  { id: 168, type: "single", kanji: "続", onyomi: "ゾク", kunyomi: "つづ(く)", meaning: "melanjutkan", meaningEn: "continue", level: "N4",
    example: { jp: "雨が続いています。", reading: "あめがつづいています。", meaning: "Hujan terus berlanjut. (The rain continues.)" } },
  { id: 169, type: "single", kanji: "変", onyomi: "ヘン", kunyomi: "か(わる)", meaning: "berubah", meaningEn: "change", level: "N4",
    example: { jp: "天気が変わりました。", reading: "てんきがかわりました。", meaning: "Cuaca sudah berubah. (The weather has changed.)" } },
  { id: 170, type: "single", kanji: "死", onyomi: "シ", kunyomi: "し(ぬ)", meaning: "mati", meaningEn: "die", level: "N4",
    example: { jp: "祖父は去年死にました。", reading: "そふはきょねんしにました。", meaning: "Kakek meninggal tahun lalu. (Grandfather died last year.)" } },
  { id: 171, type: "single", kanji: "育", onyomi: "イク", kunyomi: "そだ(つ)", meaning: "membesarkan, tumbuh", meaningEn: "raise, grow", level: "N4",
    example: { jp: "子供を育てています。", reading: "こどもをそだてています。", meaning: "Membesarkan anak. (Raising a child.)" } },
  { id: 172, type: "single", kanji: "洗", onyomi: "セン", kunyomi: "あら(う)", meaning: "mencuci", meaningEn: "wash", level: "N4",
    example: { jp: "皿を洗います。", reading: "さらをあらいます。", meaning: "Mencuci piring. (Wash the dishes.)" } },
  { id: 173, type: "single", kanji: "切", onyomi: "セツ", kunyomi: "き(る)", meaning: "memotong", meaningEn: "cut", level: "N4",
    example: { jp: "野菜を切ります。", reading: "やさいをきります。", meaning: "Memotong sayuran. (Cut vegetables.)" } },
  { id: 174, type: "single", kanji: "自", onyomi: "ジ", kunyomi: "みずか(ら)", meaning: "diri sendiri", meaningEn: "self", level: "N4",
    example: { jp: "自分でやります。", reading: "じぶんでやります。", meaning: "Melakukannya sendiri. (I'll do it myself.)" } },
  { id: 175, type: "single", kanji: "用", onyomi: "ヨウ", kunyomi: "もち(いる)", meaning: "menggunakan, keperluan", meaningEn: "use, business", level: "N4",
    example: { jp: "用があります。", reading: "ようがあります。", meaning: "Ada keperluan. (I have some business/errand.)" } },
  { id: 176, type: "single", kanji: "心", onyomi: "シン", kunyomi: "こころ", meaning: "hati, pikiran", meaningEn: "heart, mind", level: "N4",
    example: { jp: "心から感謝します。", reading: "こころからかんしゃします。", meaning: "Berterima kasih dari lubuk hati. (Thank you from my heart.)" } },
  { id: 177, type: "single", kanji: "味", onyomi: "ミ", kunyomi: "あじ", meaning: "rasa", meaningEn: "taste", level: "N4",
    example: { jp: "この料理は味がいいです。", reading: "このりょうりはあじがいいです。", meaning: "Masakan ini rasanya enak. (This dish tastes good.)" } },
  { id: 178, type: "single", kanji: "悪", onyomi: "アク", kunyomi: "わる(い)", meaning: "buruk", meaningEn: "bad", level: "N4",
    example: { jp: "天気が悪いです。", reading: "てんきがわるいです。", meaning: "Cuacanya buruk. (The weather is bad.)" } },
  { id: 179, type: "single", kanji: "楽", onyomi: "ラク・ガク", kunyomi: "たの(しい)", meaning: "senang, musik", meaningEn: "fun, music", level: "N4",
    example: { jp: "音楽を聞くのが楽しいです。", reading: "おんがくをきくのがたのしいです。", meaning: "Mendengarkan musik itu menyenangkan. (Listening to music is fun.)" } },
  { id: 180, type: "single", kanji: "好", onyomi: "コウ", kunyomi: "す(き)", meaning: "suka", meaningEn: "like", level: "N4",
    example: { jp: "日本料理が好きです。", reading: "にほんりょうりがすきです。", meaning: "Suka masakan Jepang. (I like Japanese food.)" } },
  { id: 181, type: "single", kanji: "悲", onyomi: "ヒ", kunyomi: "かな(しい)", meaning: "sedih", meaningEn: "sad", level: "N4",
    example: { jp: "悲しい映画を見ました。", reading: "かなしいえいがをみました。", meaning: "Menonton film sedih. (Watched a sad movie.)" } },
  { id: 182, type: "single", kanji: "有", onyomi: "ユウ", kunyomi: "あ(る)", meaning: "ada, punya", meaningEn: "exist, have", level: "N4",
    example: { jp: "この町には有名な店があります。", reading: "このまちにはゆうめいなみせがあります。", meaning: "Di kota ini ada toko yang terkenal. (There's a famous shop in this town.)" } },
  { id: 183, type: "single", kanji: "無", onyomi: "ム", kunyomi: "な(い)", meaning: "tidak ada", meaningEn: "nonexistent", level: "N4",
    example: { jp: "時間が無いです。", reading: "じかんがないです。", meaning: "Tidak ada waktu. (There's no time.)" } },
  { id: 184, type: "single", kanji: "化", onyomi: "カ", kunyomi: "ば(ける)", meaning: "berubah", meaningEn: "change, transform", level: "N4",
    example: { jp: "文化を勉強しています。", reading: "ぶんかをべんきょうしています。", meaning: "Sedang belajar budaya. (Studying culture.)" } },
  { id: 185, type: "single", kanji: "洋", onyomi: "ヨウ", kunyomi: "", meaning: "samudra, barat", meaningEn: "ocean, western", level: "N4",
    example: { jp: "洋服を買いました。", reading: "ようふくをかいました。", meaning: "Membeli pakaian ala barat. (Bought western clothes.)" } },
  { id: 186, type: "single", kanji: "服", onyomi: "フク", kunyomi: "", meaning: "pakaian", meaningEn: "clothes", level: "N4",
    example: { jp: "新しい服がほしいです。", reading: "あたらしいふくがほしいです。", meaning: "Ingin baju baru. (I want new clothes.)" } },
  { id: 187, type: "single", kanji: "着", onyomi: "チャク", kunyomi: "き(る)・つ(く)", meaning: "memakai, tiba", meaningEn: "wear, arrive", level: "N4",
    example: { jp: "駅に着きました。", reading: "えきにつきました。", meaning: "Sudah sampai di stasiun. (Arrived at the station.)" } },
  { id: 188, type: "single", kanji: "特", onyomi: "トク", kunyomi: "", meaning: "khusus", meaningEn: "special", level: "N4",
    example: { jp: "特に問題はありません。", reading: "とくにもんだいはありません。", meaning: "Tidak ada masalah khususnya. (There's no particular problem.)" } },
  { id: 189, type: "single", kanji: "別", onyomi: "ベツ", kunyomi: "わか(れる)", meaning: "berpisah, lain", meaningEn: "separate, other", level: "N4",
    example: { jp: "別の店に行きましょう。", reading: "べつのみせにいきましょう。", meaning: "Ayo pergi ke toko lain. (Let's go to a different shop.)" } },
  { id: 190, type: "single", kanji: "同", onyomi: "ドウ", kunyomi: "おな(じ)", meaning: "sama", meaningEn: "same", level: "N4",
    example: { jp: "同じ本を持っています。", reading: "おなじほんをもっています。", meaning: "Memiliki buku yang sama. (I have the same book.)" } },
  { id: 191, type: "single", kanji: "違", onyomi: "イ", kunyomi: "ちが(う)", meaning: "berbeda", meaningEn: "differ", level: "N4",
    example: { jp: "意見が違います。", reading: "いけんがちがいます。", meaning: "Pendapatnya berbeda. (The opinion is different.)" } },
  { id: 192, type: "single", kanji: "両", onyomi: "リョウ", kunyomi: "", meaning: "kedua", meaningEn: "both", level: "N4",
    example: { jp: "両方好きです。", reading: "りょうほうすきです。", meaning: "Suka keduanya. (I like both.)" } },
  { id: 193, type: "single", kanji: "度", onyomi: "ド", kunyomi: "たび", meaning: "derajat, kali", meaningEn: "degree, times", level: "N4",
    example: { jp: "もう一度言ってください。", reading: "もういちどいってください。", meaning: "Tolong ucapkan sekali lagi. (Please say it one more time.)" } },
  { id: 194, type: "single", kanji: "回", onyomi: "カイ", kunyomi: "まわ(る)", meaning: "kali, putar", meaningEn: "times, turn", level: "N4",
    example: { jp: "三回洗いました。", reading: "さんかいあらいました。", meaning: "Mencuci tiga kali. (Washed it three times.)" } },
  { id: 195, type: "single", kanji: "号", onyomi: "ゴウ", kunyomi: "", meaning: "nomor", meaningEn: "number", level: "N4",
    example: { jp: "三号室はどこですか。", reading: "さんごうしつはどこですか。", meaning: "Di mana ruang nomor tiga? (Where is room number three?)" } },
  { id: 196, type: "single", kanji: "台", onyomi: "ダイ", kunyomi: "", meaning: "platform, penghitung", meaningEn: "platform, counter", level: "N4",
    example: { jp: "車が一台あります。", reading: "くるまがいちだいあります。", meaning: "Ada satu mobil. (There is one car.)" } },
  { id: 197, type: "single", kanji: "階", onyomi: "カイ", kunyomi: "", meaning: "lantai", meaningEn: "floor, story", level: "N4",
    example: { jp: "二階に上がってください。", reading: "にかいにあがってください。", meaning: "Tolong naik ke lantai dua. (Please go up to the second floor.)" } },

  { id: 198, type: "compound", word: "食事", reading: "しょくじ", meaning: "makan, hidangan", meaningEn: "meal", level: "N4", parts: [88, 116],
    example: { jp: "家族と食事をします。", reading: "かぞくとしょくじをします。", meaning: "Makan bersama keluarga. (Have a meal with family.)" } },
  { id: 199, type: "compound", word: "天気", reading: "てんき", meaning: "cuaca", meaningEn: "weather", level: "N5", parts: [68, 70],
    example: { jp: "今日は天気がいいです。", reading: "きょうはてんきがいいです。", meaning: "Hari ini cuacanya bagus. (The weather is nice today.)" } },
  { id: 200, type: "compound", word: "元気", reading: "げんき", meaning: "sehat, bersemangat", meaningEn: "healthy, energetic", level: "N5", parts: [115, 70],
    example: { jp: "毎日元気に過ごしています。", reading: "まいにちげんきにすごしています。", meaning: "Menjalani hari dengan sehat setiap hari. (Living energetically every day.)" } },
  { id: 201, type: "compound", word: "大学", reading: "だいがく", meaning: "universitas", meaningEn: "university", level: "N5", parts: [95, 58],
    example: { jp: "大学で経済を勉強しています。", reading: "だいがくでけいざいをべんきょうしています。", meaning: "Belajar ekonomi di universitas. (Studying economics at university.)" } },
  { id: 202, type: "compound", word: "小学校", reading: "しょうがっこう", meaning: "sekolah dasar", meaningEn: "elementary school", level: "N5", parts: [96, 58, 59],
    example: { jp: "弟は小学校に通っています。", reading: "おとうとはしょうがっこうにかよっています。", meaning: "Adik laki-laki bersekolah di SD. (My younger brother attends elementary school.)" } },
  { id: 203, type: "compound", word: "中学校", reading: "ちゅうがっこう", meaning: "sekolah menengah pertama", meaningEn: "junior high school", level: "N5", parts: [36, 58, 59],
    example: { jp: "中学校で英語を習いました。", reading: "ちゅうがっこうでえいごをならいました。", meaning: "Belajar bahasa Inggris di SMP. (Learned English at junior high school.)" } },
  { id: 204, type: "compound", word: "高校", reading: "こうこう", meaning: "sekolah menengah atas", meaningEn: "high school", level: "N5", parts: [97, 59],
    example: { jp: "高校を卒業しました。", reading: "こうこうをそつぎょうしました。", meaning: "Lulus dari SMA. (Graduated from high school.)" } },
  { id: 205, type: "compound", word: "先生", reading: "せんせい", meaning: "guru", meaningEn: "teacher", level: "N5", parts: [30, 60],
    example: { jp: "田中先生はとても優しいです。", reading: "たなかせんせいはとてもやさしいです。", meaning: "Guru Tanaka sangat baik hati. (Teacher Tanaka is very kind.)" } },
  { id: 206, type: "compound", word: "学生", reading: "がくせい", meaning: "murid, mahasiswa", meaningEn: "student", level: "N5", parts: [58, 60],
    example: { jp: "私は大学の学生です。", reading: "わたしはだいがくのがくせいです。", meaning: "Saya mahasiswa universitas. (I'm a university student.)" } },
  { id: 207, type: "compound", word: "仕事", reading: "しごと", meaning: "pekerjaan", meaningEn: "work, job", level: "N4", parts: [132, 116],
    example: { jp: "新しい仕事を始めました。", reading: "あたらしいしごとをはじめました。", meaning: "Memulai pekerjaan baru. (Started a new job.)" } },
  { id: 208, type: "compound", word: "曜日", reading: "ようび", meaning: "hari (dalam seminggu)", meaningEn: "day of the week", level: "N5", parts: [22, 15],
    example: { jp: "今日は何曜日ですか。", reading: "きょうはなんようびですか。", meaning: "Hari ini hari apa? (What day of the week is it today?)" } },
  { id: 209, type: "compound", word: "今日", reading: "きょう", meaning: "hari ini", meaningEn: "today", level: "N5", parts: [27, 15],
    example: { jp: "今日は忙しいです。", reading: "きょうはいそがしいです。", meaning: "Hari ini sibuk. (Today is busy.)" } },
  { id: 210, type: "compound", word: "来週", reading: "らいしゅう", meaning: "minggu depan", meaningEn: "next week", level: "N5", parts: [80, 29],
    example: { jp: "来週試験があります。", reading: "らいしゅうしけんがあります。", meaning: "Minggu depan ada ujian. (There's an exam next week.)" } },
  { id: 211, type: "compound", word: "先週", reading: "せんしゅう", meaning: "minggu lalu", meaningEn: "last week", level: "N5", parts: [30, 29],
    example: { jp: "先週映画を見ました。", reading: "せんしゅうえいがをみました。", meaning: "Menonton film minggu lalu. (Watched a movie last week.)" } },
  { id: 212, type: "compound", word: "午後", reading: "ごご", meaning: "siang, sore", meaningEn: "afternoon, p.m.", level: "N5", parts: [33, 31],
    example: { jp: "午後三時に会いましょう。", reading: "ごごさんじにあいましょう。", meaning: "Ayo bertemu jam tiga sore. (Let's meet at 3pm.)" } },
  { id: 213, type: "compound", word: "午前", reading: "ごぜん", meaning: "pagi", meaningEn: "morning, a.m.", level: "N5", parts: [33, 32],
    example: { jp: "午前中に宿題をします。", reading: "ごぜんちゅうにしゅくだいをします。", meaning: "Mengerjakan PR di pagi hari. (Do homework in the morning.)" } },
  { id: 214, type: "compound", word: "半分", reading: "はんぶん", meaning: "setengah", meaningEn: "half", level: "N5", parts: [26, 25],
    example: { jp: "ケーキを半分に切りました。", reading: "けーきをはんぶんにきりました。", meaning: "Memotong kue menjadi setengah. (Cut the cake in half.)" } },
  { id: 215, type: "compound", word: "外国", reading: "がいこく", meaning: "luar negeri", meaningEn: "foreign country", level: "N4", parts: [37, 110],
    example: { jp: "外国で働きたいです。", reading: "がいこくではたらきたいです。", meaning: "Ingin bekerja di luar negeri. (I want to work abroad.)" } },
  { id: 216, type: "compound", word: "全部", reading: "ぜんぶ", meaning: "semua", meaningEn: "all, everything", level: "N4", parts: [126, 127],
    example: { jp: "宿題を全部終わらせました。", reading: "しゅくだいをぜんぶおわらせました。", meaning: "Menyelesaikan semua PR. (Finished all the homework.)" } },
  { id: 217, type: "compound", word: "部屋", reading: "へや", meaning: "kamar", meaningEn: "room", level: "N4", parts: [127, 128],
    example: { jp: "部屋を掃除します。", reading: "へやをそうじします。", meaning: "Membersihkan kamar. (Clean the room.)" } },
  { id: 218, type: "compound", word: "病院", reading: "びょういん", meaning: "rumah sakit", meaningEn: "hospital", level: "N4", parts: [139, 140],
    example: { jp: "病院で診察を受けました。", reading: "びょういんでしんさつをうけました。", meaning: "Diperiksa di rumah sakit. (Got examined at the hospital.)" } },
  { id: 219, type: "compound", word: "医者", reading: "いしゃ", meaning: "dokter", meaningEn: "doctor", level: "N4", parts: [141, 142],
    example: { jp: "医者に相談しました。", reading: "いしゃにそうだんしました。", meaning: "Berkonsultasi dengan dokter. (Consulted with the doctor.)" } },
  { id: 220, type: "compound", word: "図書館", reading: "としょかん", meaning: "perpustakaan", meaningEn: "library", level: "N4", parts: [137, 86, 138],
    example: { jp: "図書館で静かに勉強します。", reading: "としょかんでしずかにべんきょうします。", meaning: "Belajar dengan tenang di perpustakaan. (Study quietly at the library.)" } },
  { id: 221, type: "compound", word: "教室", reading: "きょうしつ", meaning: "ruang kelas", meaningEn: "classroom", level: "N4", parts: [135, 136],
    example: { jp: "教室に学生が集まります。", reading: "きょうしつにがくせいがあつまります。", meaning: "Murid-murid berkumpul di ruang kelas. (Students gather in the classroom.)" } },
  { id: 222, type: "compound", word: "作業", reading: "さぎょう", meaning: "pekerjaan, operasi", meaningEn: "work, operation", level: "N4", parts: [144, 131],
    example: { jp: "みんなで作業を続けます。", reading: "みんなでさぎょうをつづけます。", meaning: "Melanjutkan pekerjaan bersama-sama. (Continue the work together.)" } },
  { id: 223, type: "compound", word: "開始", reading: "かいし", meaning: "mulai", meaningEn: "start, commencement", level: "N4", parts: [147, 145],
    example: { jp: "会議は九時に開始します。", reading: "かいぎはくじにかいしします。", meaning: "Rapat dimulai jam sembilan. (The meeting starts at nine.)" } },
  { id: 224, type: "compound", word: "質問", reading: "しつもん", meaning: "pertanyaan", meaningEn: "question", level: "N4", parts: [165, 164],
    example: { jp: "何か質問がありますか。", reading: "なにかしつもんがありますか。", meaning: "Ada pertanyaan? (Do you have any questions?)" } },
  { id: 225, type: "compound", word: "有名", reading: "ゆうめい", meaning: "terkenal", meaningEn: "famous", level: "N4", parts: [182, 57],
    example: { jp: "この店は有名です。", reading: "このみせはゆうめいです。", meaning: "Toko ini terkenal. (This shop is famous.)" } },
  { id: 226, type: "compound", word: "特別", reading: "とくべつ", meaning: "istimewa", meaningEn: "special", level: "N4", parts: [188, 189],
    example: { jp: "今日は特別な日です。", reading: "きょうはとくべつなひです。", meaning: "Hari ini hari istimewa. (Today is a special day.)" } },
  { id: 227, type: "compound", word: "同時", reading: "どうじ", meaning: "bersamaan", meaningEn: "simultaneous", level: "N4", parts: [190, 24],
    example: { jp: "二つの仕事を同時にします。", reading: "ふたつのしごとをどうじにします。", meaning: "Melakukan dua pekerjaan secara bersamaan. (Do two jobs at the same time.)" } }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { RAW };
}
