/*
 * 言葉 Kotoba — vocabulary flashcards from "Minna no Nihongo II", Pelajaran 26-32.
 * Source: "Kotoba Minna no Nihongo II.pdf" in this repo. That file is a scanned
 * extract of the Kosa Kata pages only, so it holds two pages per lesson:
 * lesson N is on PDF pages 2N-49 and 2N-48 (26 → p.3-4, 30 → p.11-12,
 * 32 → p.15-16). The first page carries "I. Kosa Kata", the second carries
 * 〈会話〉 and 〈読み物〉. The PDF runs to Pelajaran 50.
 *
 * Entries marked ※ in the book are proper nouns and fictional names
 * (※エドヤストア, ※ピカソ, ※ヨーロッパ). They are skipped.
 *
 * Each entry: kana (main word, shown big on the front — hiragana/katakana
 * first so the word is learned by sound before the kanji), kanji (may be
 * null when the source gives no kanji), context (the "[~に…]" usage note
 * from the book, if any), type (short Indonesian part-of-speech badge),
 * meaning (Indonesian gloss from the book).
 *
 * New lessons are always appended at the end of the array, never inserted
 * in the middle — kotoba-app.js derives each card's SRS key from its
 * position in this array, so reordering existing entries would reset
 * everyone's review progress.
 */

const KOTOBA = [
  { lesson: 26, kana: "みます", kanji: "見ます、診ます", type: "Kata Kerja II", meaning: "melihat, memeriksa" },
  { lesson: 26, kana: "さがします", kanji: "探します、捜します", type: "Kata Kerja I", meaning: "mencari" },
  { lesson: 26, kana: "おくれます", kanji: "遅れます", context: "[じかんに〜]", type: "Kata Kerja II", meaning: "terlambat [pada waktu]" },
  { lesson: 26, kana: "まにあいます", kanji: "間に合います", context: "[じかんに〜]", type: "Kata Kerja I", meaning: "sempat [pada waktu]" },
  { lesson: 26, kana: "やります", kanji: null, type: "Kata Kerja I", meaning: "melakukan" },
  { lesson: 26, kana: "ひろいます", kanji: "拾います", type: "Kata Kerja I", meaning: "mendapat, mengambil" },
  { lesson: 26, kana: "れんらくします", kanji: "連絡します", type: "Kata Kerja III", meaning: "menghubungi" },
  { lesson: 26, kana: "きぶんがいい", kanji: "気分がいい", type: "Ungkapan", meaning: "rasa enak, segar" },
  { lesson: 26, kana: "きぶんがわるい", kanji: "気分が悪い", type: "Ungkapan", meaning: "rasa tidak enak" },
  { lesson: 26, kana: "うんどうかい", kanji: "運動会", type: "Kata Benda", meaning: "lomba olahraga" },
  { lesson: 26, kana: "ぼんおどり", kanji: "盆踊り", type: "Kata Benda", meaning: "tarian Bon" },
  { lesson: 26, kana: "フリーマーケット", kanji: null, type: "Kata Benda", meaning: "pasar rombengan" },
  { lesson: 26, kana: "ばしょ", kanji: "場所", type: "Kata Benda", meaning: "tempat" },
  { lesson: 26, kana: "ボランティア", kanji: null, type: "Kata Benda", meaning: "sukarelawan" },
  { lesson: 26, kana: "さいふ", kanji: "財布", type: "Kata Benda", meaning: "dompet" },
  { lesson: 26, kana: "ごみ", kanji: null, type: "Kata Benda", meaning: "sampah" },
  { lesson: 26, kana: "こっかいぎじどう", kanji: "国会議事堂", type: "Kata Benda", meaning: "gedung parlemen" },
  { lesson: 26, kana: "へいじつ", kanji: "平日", type: "Kata Benda", meaning: "hari kerja" },
  { lesson: 26, kana: "〜べん", kanji: "〜弁", type: "Sufiks", meaning: "dialek 〜" },
  { lesson: 26, kana: "こんど", kanji: "今度", type: "Kata Benda", meaning: "kali ini, lain kali" },
  { lesson: 26, kana: "ずいぶん", kanji: null, type: "Kata Keterangan", meaning: "sangat, amat" },
  { lesson: 26, kana: "ちょくせつ", kanji: "直接", type: "Kata Keterangan", meaning: "langsung" },
  { lesson: 26, kana: "いつでも", kanji: null, type: "Ungkapan", meaning: "kapan saja" },
  { lesson: 26, kana: "どこでも", kanji: null, type: "Ungkapan", meaning: "di mana-mana" },
  { lesson: 26, kana: "だれでも", kanji: null, type: "Ungkapan", meaning: "siapa saja" },
  { lesson: 26, kana: "なんでも", kanji: "何でも", type: "Ungkapan", meaning: "apa saja" },
  { lesson: 26, kana: "こんな〜", kanji: null, type: "Ungkapan", meaning: "〜 begini" },
  { lesson: 26, kana: "そんな〜", kanji: null, type: "Ungkapan", meaning: "〜 begitu (dekat dari lawan bicara)" },
  { lesson: 26, kana: "あんな〜", kanji: null, type: "Ungkapan", meaning: "〜 begitu (jauh dari si pembicara dan lawan bicara)" },

  { lesson: 26, kana: "かたづきます", kanji: "片づきます", context: "[荷物が〜]", type: "Kata Kerja I", meaning: "membereskan [barang]" },
  { lesson: 26, kana: "だします", kanji: "出します", context: "[ごみを〜]", type: "Kata Kerja I", meaning: "membuang [sampah], mengeluarkan" },
  { lesson: 26, kana: "もえるごみ", kanji: "燃えるごみ", type: "Kata Benda", meaning: "sampah organik" },
  { lesson: 26, kana: "おきば", kanji: "置き場", type: "Kata Benda", meaning: "tempat meletakkan sampah" },
  { lesson: 26, kana: "よこ", kanji: "横", type: "Kata Benda", meaning: "sebelah, samping" },
  { lesson: 26, kana: "びん", kanji: "瓶", type: "Kata Benda", meaning: "botol" },
  { lesson: 26, kana: "かん", kanji: "缶", type: "Kata Benda", meaning: "kaleng" },
  { lesson: 26, kana: "ガス", kanji: null, type: "Kata Benda", meaning: "gas" },
  { lesson: 26, kana: "〜がいしゃ", kanji: "〜会社", type: "Sufiks", meaning: "perusahaan 〜" },

  { lesson: 26, kana: "うちゅう", kanji: "宇宙", type: "Kata Benda", meaning: "angkasa" },
  { lesson: 26, kana: "〜さま", kanji: "〜様", type: "Sufiks", meaning: "kepada Yth. 〜, Bapak 〜, Ibu 〜, Sdr. 〜 (kata hormat dari 〜さん)" },
  { lesson: 26, kana: "うちゅうせん", kanji: "宇宙船", type: "Kata Benda", meaning: "wahana antariksa" },
  { lesson: 26, kana: "こわい", kanji: "怖い", type: "Kata Sifat", meaning: "takut" },
  { lesson: 26, kana: "うちゅうステーション", kanji: "宇宙ステーション", type: "Kata Benda", meaning: "stasiun luar angkasa" },
  { lesson: 26, kana: "ちがいます", kanji: "違います", type: "Kata Kerja I", meaning: "tidak benar" },
  { lesson: 26, kana: "うちゅうひこうし", kanji: "宇宙飛行士", type: "Kata Benda", meaning: "astronot" },

  // ---- Pelajaran 27 ----
  { lesson: 27, kana: "かいます", kanji: "飼います", type: "Kata Kerja I", meaning: "memelihara" },
  { lesson: 27, kana: "はしります", kanji: "走ります", context: "[みちを〜]", type: "Kata Kerja I", meaning: "berlari [jalan]" },
  { lesson: 27, kana: "みえます", kanji: "見えます", context: "[やまが〜]", type: "Kata Kerja II", meaning: "[gunung] terlihat" },
  { lesson: 27, kana: "きこえます", kanji: "聞こえます", context: "[おとが〜]", type: "Kata Kerja II", meaning: "[bunyi] terdengar" },
  { lesson: 27, kana: "できます", kanji: null, context: "[みちが〜]", type: "Kata Kerja II", meaning: "[jalan] dibuat" },
  { lesson: 27, kana: "ひらきます", kanji: "開きます", context: "[きょうしつを〜]", type: "Kata Kerja I", meaning: "membuka/mengadakan [kelas]" },
  { lesson: 27, kana: "しんぱい", kanji: "心配", type: "Kata Sifat", meaning: "khawatir" },
  { lesson: 27, kana: "ペット", kanji: null, type: "Kata Benda", meaning: "hewan peliharaan" },
  { lesson: 27, kana: "とり", kanji: "鳥", type: "Kata Benda", meaning: "burung" },
  { lesson: 27, kana: "こえ", kanji: "声", type: "Kata Benda", meaning: "suara" },
  { lesson: 27, kana: "なみ", kanji: "波", type: "Kata Benda", meaning: "ombak, gelombang" },
  { lesson: 27, kana: "はなび", kanji: "花火", type: "Kata Benda", meaning: "kembang api" },
  { lesson: 27, kana: "どうぐ", kanji: "道具", type: "Kata Benda", meaning: "alat" },
  { lesson: 27, kana: "クリーニング", kanji: null, type: "Kata Benda", meaning: "laundry" },
  { lesson: 27, kana: "いえ", kanji: "家", type: "Kata Benda", meaning: "rumah" },
  { lesson: 27, kana: "マンション", kanji: null, type: "Kata Benda", meaning: "apartmen" },
  { lesson: 27, kana: "キッチン", kanji: null, type: "Kata Benda", meaning: "dapur" },
  { lesson: 27, kana: "〜きょうしつ", kanji: "〜教室", type: "Sufiks", meaning: "les 〜, kelas 〜" },
  { lesson: 27, kana: "パーティールーム", kanji: null, type: "Kata Benda", meaning: "ruang pesta" },
  { lesson: 27, kana: "かた", kanji: "方", type: "Kata Benda", meaning: "orang (Kata Hormat dari ひと)" },
  { lesson: 27, kana: "〜ご", kanji: "〜後", type: "Sufiks", meaning: "setelah 〜, sesudah 〜" },
  { lesson: 27, kana: "〜しか", kanji: null, type: "Sufiks", meaning: "hanya 〜 (dipakai bersama dengan kata bentuk negatif)" },
  { lesson: 27, kana: "ほかの", kanji: null, type: "Kata Sifat", meaning: "lain" },
  { lesson: 27, kana: "はっきり", kanji: null, type: "Kata Keterangan", meaning: "jelas" },

  { lesson: 27, kana: "かぐ", kanji: "家具", type: "Kata Benda", meaning: "perabot rumah, mebel" },
  { lesson: 27, kana: "ほんだな", kanji: "本棚", type: "Kata Benda", meaning: "lemari buku" },
  { lesson: 27, kana: "いつか", kanji: null, type: "Kata Keterangan", meaning: "kapan-kapan" },
  { lesson: 27, kana: "たてます", kanji: "建てます", type: "Kata Kerja II", meaning: "membangun" },
  { lesson: 27, kana: "すばらしい", kanji: null, type: "Kata Sifat", meaning: "bagus" },

  { lesson: 27, kana: "こどもたち", kanji: "子どもたち", type: "Kata Benda", meaning: "anak-anak" },
  { lesson: 27, kana: "だいすき", kanji: "大好き", type: "Kata Sifat", meaning: "kesukaan" },
  { lesson: 27, kana: "しゅじんこう", kanji: "主人公", type: "Kata Benda", meaning: "pelaku utama" },
  { lesson: 27, kana: "かたち", kanji: "形", type: "Kata Benda", meaning: "sosok, bentuk" },
  { lesson: 27, kana: "ふしぎ", kanji: "不思議", type: "Kata Sifat", meaning: "ajaib" },
  { lesson: 27, kana: "ポケット", kanji: null, type: "Kata Benda", meaning: "kantong" },
  { lesson: 27, kana: "たとえば", kanji: "例えば", type: "Kata Keterangan", meaning: "misalnya" },
  { lesson: 27, kana: "つけます", kanji: "付けます", type: "Kata Kerja II", meaning: "memasang" },
  { lesson: 27, kana: "じゆうに", kanji: "自由に", type: "Kata Keterangan", meaning: "dengan bebas" },
  { lesson: 27, kana: "そら", kanji: "空", type: "Kata Benda", meaning: "langit" },
  { lesson: 27, kana: "とびます", kanji: "飛びます", type: "Kata Kerja I", meaning: "terbang" },
  { lesson: 27, kana: "むかし", kanji: "昔", type: "Kata Benda", meaning: "dulu" },
  { lesson: 27, kana: "じぶん", kanji: "自分", type: "Kata Benda", meaning: "diri sendiri" },
  { lesson: 27, kana: "しょうらい", kanji: "将来", type: "Kata Benda", meaning: "masa depan" },

  // ---- Pelajaran 28 ----
  { lesson: 28, kana: "うれます", kanji: "売れます", context: "[パンが〜]", type: "Kata Kerja II", meaning: "[roti] terjual" },
  { lesson: 28, kana: "おどります", kanji: "踊ります", type: "Kata Kerja I", meaning: "menari" },
  { lesson: 28, kana: "かみます", kanji: null, type: "Kata Kerja I", meaning: "makan, menggigit" },
  { lesson: 28, kana: "えらびます", kanji: "選びます", type: "Kata Kerja I", meaning: "memilih" },
  { lesson: 28, kana: "かよいます", kanji: "通います", context: "[だいがくに〜]", type: "Kata Kerja I", meaning: "pergi [ke universitas]" },
  { lesson: 28, kana: "メモします", kanji: null, type: "Kata Kerja III", meaning: "mencatat" },
  { lesson: 28, kana: "まじめ", kanji: null, type: "Kata Sifat", meaning: "serius" },
  { lesson: 28, kana: "ねっしん", kanji: "熱心", type: "Kata Sifat", meaning: "tekun" },
  { lesson: 28, kana: "えらい", kanji: "偉い", type: "Kata Sifat", meaning: "hebat" },
  { lesson: 28, kana: "ちょうどいい", kanji: null, type: "Ungkapan", meaning: "pas, cocok" },
  { lesson: 28, kana: "けしき", kanji: "景色", type: "Kata Benda", meaning: "pemandangan" },
  { lesson: 28, kana: "びよういん", kanji: "美容院", type: "Kata Benda", meaning: "salon kecantikan" },
  { lesson: 28, kana: "だいどころ", kanji: "台所", type: "Kata Benda", meaning: "dapur" },
  { lesson: 28, kana: "けいけん", kanji: "経験", type: "Kata Benda", meaning: "pengalaman (〜があります: berpengalaman, 〜をします: mengalami)" },
  { lesson: 28, kana: "ちから", kanji: "力", type: "Kata Benda", meaning: "tenaga" },
  { lesson: 28, kana: "にんき", kanji: "人気", type: "Kata Benda", meaning: "populer/disenangi ([がくせいに]〜があります: populer [di kalangan mahasiswa])" },
  { lesson: 28, kana: "かたち", kanji: "形", type: "Kata Benda", meaning: "bentuk, sosok" },
  { lesson: 28, kana: "いろ", kanji: "色", type: "Kata Benda", meaning: "warna" },
  { lesson: 28, kana: "あじ", kanji: "味", type: "Kata Benda", meaning: "rasa" },
  { lesson: 28, kana: "ガム", kanji: null, type: "Kata Benda", meaning: "permen karet" },
  { lesson: 28, kana: "しなもの", kanji: "品物", type: "Kata Benda", meaning: "barang" },
  { lesson: 28, kana: "ねだん", kanji: "値段", type: "Kata Benda", meaning: "harga" },
  { lesson: 28, kana: "きゅうりょう", kanji: "給料", type: "Kata Benda", meaning: "gaji" },
  { lesson: 28, kana: "ボーナス", kanji: null, type: "Kata Benda", meaning: "bonus" },
  { lesson: 28, kana: "ゲーム", kanji: null, type: "Kata Benda", meaning: "permainan, game" },
  { lesson: 28, kana: "ばんぐみ", kanji: "番組", type: "Kata Benda", meaning: "acara TV" },
  { lesson: 28, kana: "ドラマ", kanji: null, type: "Kata Benda", meaning: "drama" },
  { lesson: 28, kana: "かしゅ", kanji: "歌手", type: "Kata Benda", meaning: "penyanyi" },
  { lesson: 28, kana: "しょうせつ", kanji: "小説", type: "Kata Benda", meaning: "novel" },
  { lesson: 28, kana: "しょうせつか", kanji: "小説家", type: "Kata Benda", meaning: "novelis" },
  { lesson: 28, kana: "〜か", kanji: "〜家", type: "Sufiks", meaning: "aliran 〜" },
  { lesson: 28, kana: "〜き", kanji: "〜機", type: "Sufiks", meaning: "mesin 〜" },
  { lesson: 28, kana: "むすこ", kanji: "息子", type: "Kata Benda", meaning: "anak laki-laki" },
  { lesson: 28, kana: "むすこさん", kanji: "息子さん", type: "Kata Benda", meaning: "putra" },
  { lesson: 28, kana: "むすめ", kanji: "娘", type: "Kata Benda", meaning: "anak perempuan" },
  { lesson: 28, kana: "むすめさん", kanji: "娘さん", type: "Kata Benda", meaning: "putri" },
  { lesson: 28, kana: "じぶん", kanji: "自分", type: "Kata Benda", meaning: "diri sendiri" },
  { lesson: 28, kana: "しょうらい", kanji: "将来", type: "Kata Benda", meaning: "masa depan" },
  { lesson: 28, kana: "しばらく", kanji: null, type: "Kata Keterangan", meaning: "sebentar, sementara" },
  { lesson: 28, kana: "たいてい", kanji: null, type: "Kata Keterangan", meaning: "kebanyakan" },
  { lesson: 28, kana: "それに", kanji: null, type: "Ungkapan", meaning: "dan juga" },
  { lesson: 28, kana: "それで", kanji: null, type: "Ungkapan", meaning: "dan, lalu" },

  { lesson: 28, kana: "おねがいがあるんですが", kanji: "お願いがあるんですが", context: "[ちょっと〜]", type: "Ungkapan", meaning: "Minta sesuatu [sebentar]." },
  { lesson: 28, kana: "じつは", kanji: "実は", type: "Kata Keterangan", meaning: "solanya/sebenarnya" },
  { lesson: 28, kana: "かいわ", kanji: "会話", type: "Kata Benda", meaning: "percakapan" },
  { lesson: 28, kana: "うーん", kanji: null, type: "Ungkapan", meaning: "mmm..." },

  { lesson: 28, kana: "おしらせ", kanji: "お知らせ", type: "Kata Benda", meaning: "pemberitahuan, pengumuman" },
  { lesson: 28, kana: "さんかします", kanji: "参加します", type: "Kata Kerja III", meaning: "mengikuti" },
  { lesson: 28, kana: "ひにち", kanji: "日にち", type: "Kata Benda", meaning: "tanggal" },
  { lesson: 28, kana: "ど", kanji: "土", type: "Kata Benda", meaning: "hari Sabtu" },
  { lesson: 28, kana: "たいいくかん", kanji: "体育館", type: "Kata Benda", meaning: "gedung olahraga" },
  { lesson: 28, kana: "むりょう", kanji: "無料", type: "Kata Benda", meaning: "gratis, cuma-cuma" },
  { lesson: 28, kana: "さそいます", kanji: "誘います", type: "Kata Kerja I", meaning: "mengajak" },
  { lesson: 28, kana: "イベント", kanji: null, type: "Kata Benda", meaning: "acara" },

  // ---- Pelajaran 29 ----
  { lesson: 29, kana: "あきます", kanji: "開きます", context: "[ドアが〜]", type: "Kata Kerja I", meaning: "[pintu] terbuka" },
  { lesson: 29, kana: "しまります", kanji: "閉まります", context: "[ドアが〜]", type: "Kata Kerja I", meaning: "[pintu] tertutup" },
  { lesson: 29, kana: "つきます", kanji: null, context: "[でんきが〜]", type: "Kata Kerja I", meaning: "[lampu] menyala" },
  { lesson: 29, kana: "きえます", kanji: "消えます", context: "[でんきが〜]", type: "Kata Kerja II", meaning: "[lampu] terpadam" },
  { lesson: 29, kana: "こわれます", kanji: "壊れます", context: "[いすが〜]", type: "Kata Kerja II", meaning: "[kursi] rusak" },
  { lesson: 29, kana: "われます", kanji: "割れます", context: "[コップが〜]", type: "Kata Kerja II", meaning: "[gelas] pecah" },
  { lesson: 29, kana: "おれます", kanji: "折れます", context: "[きが〜]", type: "Kata Kerja II", meaning: "[pohon] patah" },
  { lesson: 29, kana: "やぶれます", kanji: "破れます", context: "[かみが〜]", type: "Kata Kerja II", meaning: "[kertas] robek" },
  { lesson: 29, kana: "よごれます", kanji: "汚れます", context: "[ふくが〜]", type: "Kata Kerja II", meaning: "[baju] menjadi kotor" },
  { lesson: 29, kana: "つきます", kanji: "付きます", context: "[ポケットが〜]", type: "Kata Kerja I", meaning: "[kantong] terpasang" },
  { lesson: 29, kana: "はずれます", kanji: "外れます", context: "[ボタンが〜]", type: "Kata Kerja II", meaning: "[kancing] terlepas" },
  { lesson: 29, kana: "とまります", kanji: "止まります", context: "[くるまが〜]", type: "Kata Kerja I", meaning: "[mobil] berhenti" },
  { lesson: 29, kana: "まちがえます", kanji: null, type: "Kata Kerja II", meaning: "bersalah" },
  { lesson: 29, kana: "おとします", kanji: "落とします", type: "Kata Kerja I", meaning: "menjatuhkan, kehilangan" },
  { lesson: 29, kana: "かかります", kanji: "掛かります", context: "[かぎが〜]", type: "Kata Kerja I", meaning: "terkunci" },
  { lesson: 29, kana: "ふきます", kanji: null, type: "Kata Kerja I", meaning: "mengelap" },
  { lesson: 29, kana: "とりかえます", kanji: "取り替えます", type: "Kata Kerja II", meaning: "mengganti" },
  { lesson: 29, kana: "かたづけます", kanji: "片づけます", type: "Kata Kerja II", meaning: "membereskan" },
  { lesson: 29, kana: "おさら", kanji: "お皿", type: "Kata Benda", meaning: "piring" },
  { lesson: 29, kana: "おちゃわん", kanji: null, type: "Kata Benda", meaning: "mangkuk" },
  { lesson: 29, kana: "コップ", kanji: null, type: "Kata Benda", meaning: "gelas" },
  { lesson: 29, kana: "ガラス", kanji: null, type: "Kata Benda", meaning: "kaca" },
  { lesson: 29, kana: "ふくろ", kanji: "袋", type: "Kata Benda", meaning: "kantong" },
  { lesson: 29, kana: "しょるい", kanji: "書類", type: "Kata Benda", meaning: "dokumen" },
  { lesson: 29, kana: "えだ", kanji: "枝", type: "Kata Benda", meaning: "ranting" },
  { lesson: 29, kana: "えきいん", kanji: "駅員", type: "Kata Benda", meaning: "petugas stasiun" },
  { lesson: 29, kana: "こうばん", kanji: "交番", type: "Kata Benda", meaning: "pos polisi" },
  { lesson: 29, kana: "スピーチ", kanji: null, type: "Kata Benda", meaning: "pidato (〜をします: berpidato)" },
  { lesson: 29, kana: "へんじ", kanji: "返事", type: "Kata Benda", meaning: "jawaban (〜をします: memberi jawaban)" },
  { lesson: 29, kana: "おさきにどうぞ", kanji: "お先にどうぞ", type: "Ungkapan", meaning: "Silakan duluan!" },

  { lesson: 29, kana: "いまのでんしゃ", kanji: "今の電車", type: "Kata Benda", meaning: "kereta tadi" },
  { lesson: 29, kana: "わすれもの", kanji: "忘れ物", type: "Kata Benda", meaning: "barang yang tertinggal, ketinggalan" },
  { lesson: 29, kana: "このくらい", kanji: null, type: "Ungkapan", meaning: "segini" },
  { lesson: 29, kana: "〜がわ", kanji: "〜側", type: "Sufiks", meaning: "sebelah 〜" },
  { lesson: 29, kana: "ポケット", kanji: null, type: "Kata Benda", meaning: "kantong" },
  { lesson: 29, kana: "〜へん", kanji: "〜辺", type: "Sufiks", meaning: "sekitar 〜" },
  { lesson: 29, kana: "おぼえていません", kanji: "覚えていません", type: "Ungkapan", meaning: "Tidak ingat." },
  { lesson: 29, kana: "あみだな", kanji: "網棚", type: "Kata Benda", meaning: "rak bagasi" },
  { lesson: 29, kana: "たしか", kanji: "確か", type: "Kata Keterangan", meaning: "kalau tidak salah" },
  { lesson: 29, kana: "よかった", kanji: null, context: "[ああ、〜。]", type: "Ungkapan", meaning: "[O,] syukur. (dipakai ketika merasa lega)" },

  { lesson: 29, kana: "じしん", kanji: "地震", type: "Kata Benda", meaning: "gempa bumi" },
  { lesson: 29, kana: "かべ", kanji: "壁", type: "Kata Benda", meaning: "dinding" },
  { lesson: 29, kana: "はり", kanji: "針", type: "Kata Benda", meaning: "jarum" },
  { lesson: 29, kana: "さします", kanji: "指します", type: "Kata Kerja I", meaning: "menunjuk" },
  { lesson: 29, kana: "えきまえ", kanji: "駅前", type: "Kata Benda", meaning: "depan stasiun" },
  { lesson: 29, kana: "たおれます", kanji: "倒れます", type: "Kata Kerja II", meaning: "jatuh" },
  { lesson: 29, kana: "にし", kanji: "西", type: "Kata Benda", meaning: "barat" },
  { lesson: 29, kana: "〜のほう", kanji: "〜の方", type: "Sufiks", meaning: "sebelah 〜" },
  { lesson: 29, kana: "もえます", kanji: "燃えます", type: "Kata Kerja II", meaning: "terbakar" },
  { lesson: 29, kana: "レポーター", kanji: null, type: "Kata Benda", meaning: "wartawan, jurnalis, pelapor" },

  // ---- Pelajaran 30 ----
  { lesson: 30, kana: "はります", kanji: null, type: "Kata Kerja I", meaning: "menempelkan" },
  { lesson: 30, kana: "かけます", kanji: "掛けます", type: "Kata Kerja II", meaning: "menggantungkan" },
  { lesson: 30, kana: "かざります", kanji: "飾ります", type: "Kata Kerja I", meaning: "menghiasi" },
  { lesson: 30, kana: "ならべます", kanji: "並べます", type: "Kata Kerja II", meaning: "menata" },
  { lesson: 30, kana: "うえます", kanji: "植えます", type: "Kata Kerja II", meaning: "menanam" },
  { lesson: 30, kana: "もどします", kanji: "戻します", type: "Kata Kerja I", meaning: "mengembalikan" },
  { lesson: 30, kana: "まとめます", kanji: null, type: "Kata Kerja II", meaning: "merangkumkan" },
  { lesson: 30, kana: "しまいます", kanji: null, type: "Kata Kerja I", meaning: "menyimpan" },
  { lesson: 30, kana: "きめます", kanji: "決めます", type: "Kata Kerja II", meaning: "menentukan" },
  { lesson: 30, kana: "よしゅうします", kanji: "予習します", type: "Kata Kerja III", meaning: "belajar persiapan" },
  { lesson: 30, kana: "ふくしゅうします", kanji: "復習します", type: "Kata Kerja III", meaning: "belajar pengulangan" },
  { lesson: 30, kana: "そのままにします", kanji: null, type: "Kata Kerja III", meaning: "membiarkan begitu" },
  { lesson: 30, kana: "じゅぎょう", kanji: "授業", type: "Kata Benda", meaning: "kelas, pelajaran" },
  { lesson: 30, kana: "こうぎ", kanji: "講義", type: "Kata Benda", meaning: "kuliah" },
  { lesson: 30, kana: "ミーティング", kanji: null, type: "Kata Benda", meaning: "rapat" },
  { lesson: 30, kana: "よてい", kanji: "予定", type: "Kata Benda", meaning: "acara" },
  { lesson: 30, kana: "おしらせ", kanji: "お知らせ", type: "Kata Benda", meaning: "pengumuman" },
  { lesson: 30, kana: "ガイドブック", kanji: null, type: "Kata Benda", meaning: "buku petunjuk" },
  { lesson: 30, kana: "カレンダー", kanji: null, type: "Kata Benda", meaning: "kalender" },
  { lesson: 30, kana: "ポスター", kanji: null, type: "Kata Benda", meaning: "plakat, poster" },
  { lesson: 30, kana: "よていひょう", kanji: "予定表", type: "Kata Benda", meaning: "jadwal acara" },
  { lesson: 30, kana: "ごみばこ", kanji: "ごみ箱", type: "Kata Benda", meaning: "tempat sampah, tong sampah" },
  { lesson: 30, kana: "にんぎょう", kanji: "人形", type: "Kata Benda", meaning: "boneka, orang-orangan" },
  { lesson: 30, kana: "かびん", kanji: "花瓶", type: "Kata Benda", meaning: "vas" },
  { lesson: 30, kana: "かがみ", kanji: "鏡", type: "Kata Benda", meaning: "cermin" },
  { lesson: 30, kana: "ひきだし", kanji: "引き出し", type: "Kata Benda", meaning: "laci" },
  { lesson: 30, kana: "げんかん", kanji: "玄関", type: "Kata Benda", meaning: "ruang depan" },
  { lesson: 30, kana: "ろうか", kanji: "廊下", type: "Kata Benda", meaning: "koridor, gang" },
  { lesson: 30, kana: "かべ", kanji: "壁", type: "Kata Benda", meaning: "dinding" },
  { lesson: 30, kana: "いけ", kanji: "池", type: "Kata Benda", meaning: "kolam" },
  { lesson: 30, kana: "もとのところ", kanji: "元の所", type: "Kata Benda", meaning: "tempat semula" },
  { lesson: 30, kana: "まわり", kanji: "周り", type: "Kata Benda", meaning: "sekitar" },
  { lesson: 30, kana: "まんなか", kanji: "真ん中", type: "Kata Benda", meaning: "tengah" },
  { lesson: 30, kana: "すみ", kanji: "隅", type: "Kata Benda", meaning: "pojok, sudut" },
  { lesson: 30, kana: "まだ", kanji: null, type: "Kata Keterangan", meaning: "masih" },

  { lesson: 30, kana: "リュック", kanji: null, type: "Kata Benda", meaning: "ransel" },
  { lesson: 30, kana: "ひじょうぶくろ", kanji: "非常袋", type: "Kata Benda", meaning: "kantong darurat" },
  { lesson: 30, kana: "ひじょうじ", kanji: "非常時", type: "Kata Benda", meaning: "saat darurat" },
  { lesson: 30, kana: "せいかつします", kanji: "生活します", type: "Kata Kerja III", meaning: "hidup" },
  { lesson: 30, kana: "かいちゅうでんとう", kanji: "懐中電灯", type: "Kata Benda", meaning: "senter" },
  { lesson: 30, kana: "〜とか、〜とか", kanji: null, type: "Ungkapan", meaning: "〜 atau 〜" },

  { lesson: 30, kana: "まるい", kanji: "丸い", type: "Kata Sifat", meaning: "bundar, bulat" },
  { lesson: 30, kana: "ある〜", kanji: null, type: "Ungkapan", meaning: "suatu 〜" },
  { lesson: 30, kana: "ゆめをみます", kanji: "夢を見ます", type: "Kata Kerja II", meaning: "bermimpi" },
  { lesson: 30, kana: "うれしい", kanji: null, type: "Kata Sifat", meaning: "senang" },
  { lesson: 30, kana: "いや", kanji: "嫌", type: "Kata Sifat", meaning: "tidak senang, tidak suka" },
  { lesson: 30, kana: "すると", kanji: null, type: "Ungkapan", meaning: "kemudian" },
  { lesson: 30, kana: "めがさめます", kanji: "目が覚めます", type: "Kata Kerja II", meaning: "bangun, sadar" },

  // ---- Pelajaran 31 ----
  { lesson: 31, kana: "つづけます", kanji: "続けます", type: "Kata Kerja II", meaning: "melanjutkan" },
  { lesson: 31, kana: "みつけます", kanji: "見つけます", type: "Kata Kerja II", meaning: "menemukan" },
  { lesson: 31, kana: "とります", kanji: "取ります", context: "[やすみを〜]", type: "Kata Kerja I", meaning: "mengambil [cuti]" },
  { lesson: 31, kana: "うけます", kanji: "受けます", context: "[しけんを〜]", type: "Kata Kerja II", meaning: "mengikuti [ujian]" },
  { lesson: 31, kana: "もうしこみます", kanji: "申し込みます", type: "Kata Kerja I", meaning: "mendaftar" },
  { lesson: 31, kana: "きゅうけいします", kanji: "休憩します", type: "Kata Kerja III", meaning: "beristirahat" },
  { lesson: 31, kana: "れんきゅう", kanji: "連休", type: "Kata Benda", meaning: "liburan berturutan" },
  { lesson: 31, kana: "さくぶん", kanji: "作文", type: "Kata Benda", meaning: "karangan" },
  { lesson: 31, kana: "はっぴょう", kanji: "発表", type: "Kata Benda", meaning: "presentasi (〜します: mempresentasikan)" },
  { lesson: 31, kana: "てんらんかい", kanji: "展覧会", type: "Kata Benda", meaning: "pameran" },
  { lesson: 31, kana: "けっこんしき", kanji: "結婚式", type: "Kata Benda", meaning: "upacara pernikahan" },
  { lesson: 31, kana: "[お]そうしき", kanji: "[お]葬式", type: "Kata Benda", meaning: "upacara kematian" },
  { lesson: 31, kana: "しき", kanji: "式", type: "Kata Benda", meaning: "upacara" },
  { lesson: 31, kana: "ほんしゃ", kanji: "本社", type: "Kata Benda", meaning: "kantor pusat" },
  { lesson: 31, kana: "してん", kanji: "支店", type: "Kata Benda", meaning: "kantor cabang" },
  { lesson: 31, kana: "きょうかい", kanji: "教会", type: "Kata Benda", meaning: "gereja" },
  { lesson: 31, kana: "だいがくいん", kanji: "大学院", type: "Kata Benda", meaning: "Program S2, S3 Universitas" },
  { lesson: 31, kana: "どうぶつえん", kanji: "動物園", type: "Kata Benda", meaning: "kebun binatang" },
  { lesson: 31, kana: "おんせん", kanji: "温泉", type: "Kata Benda", meaning: "tempat pemandian air panas" },
  { lesson: 31, kana: "かえり", kanji: "帰り", type: "Kata Benda", meaning: "pulang" },
  { lesson: 31, kana: "おこさん", kanji: "お子さん", type: "Kata Benda", meaning: "anak orang lain" },
  { lesson: 31, kana: "〜ごう", kanji: "〜号", type: "Sufiks", meaning: "nomor 〜 (nomor yang dipakai untuk kereta, angin topan dan lain-lain)" },
  { lesson: 31, kana: "〜のほう", kanji: "〜の方", type: "Sufiks", meaning: "sebelah 〜" },
  { lesson: 31, kana: "ずっと", kanji: null, type: "Kata Keterangan", meaning: "seterusnya" },

  { lesson: 31, kana: "のこります", kanji: "残ります", type: "Kata Kerja I", meaning: "tinggal" },
  { lesson: 31, kana: "にゅうがくしけん", kanji: "入学試験", type: "Kata Benda", meaning: "ujian masuk" },
  { lesson: 31, kana: "つきに", kanji: "月に", type: "Ungkapan", meaning: "dalam sebulan" },

  { lesson: 31, kana: "むら", kanji: "村", type: "Kata Benda", meaning: "desa, kampung" },
  { lesson: 31, kana: "そつぎょうします", kanji: "卒業します", type: "Kata Kerja III", meaning: "lulus, tamat" },
  { lesson: 31, kana: "えいがかん", kanji: "映画館", type: "Kata Benda", meaning: "gedung bioskop" },
  { lesson: 31, kana: "いや", kanji: "嫌", type: "Kata Sifat", meaning: "tidak senang, tidak suka" },
  { lesson: 31, kana: "そら", kanji: "空", type: "Kata Benda", meaning: "langit" },
  { lesson: 31, kana: "とじます", kanji: "閉じます", type: "Kata Kerja II", meaning: "tutup" },
  { lesson: 31, kana: "とかい", kanji: "都会", type: "Kata Benda", meaning: "kota besar" },
  { lesson: 31, kana: "こどもたち", kanji: "子どもたち", type: "Kata Benda", meaning: "anak-anak" },
  { lesson: 31, kana: "じゆうに", kanji: "自由に", type: "Kata Keterangan", meaning: "dengan bebas" },

  // ---- Pelajaran 32 ----
  { lesson: 32, kana: "うんどうします", kanji: "運動します", type: "Kata Kerja III", meaning: "berolahraga" },
  { lesson: 32, kana: "せいこうします", kanji: "成功します", type: "Kata Kerja III", meaning: "berhasil" },
  { lesson: 32, kana: "しっぱいします", kanji: "失敗します", context: "[しけんに〜]", type: "Kata Kerja III", meaning: "gagal [ujian]" },
  { lesson: 32, kana: "ごうかくします", kanji: "合格します", context: "[しけんに〜]", type: "Kata Kerja III", meaning: "lulus [ujian]" },
  { lesson: 32, kana: "やみます", kanji: null, context: "[あめが〜]", type: "Kata Kerja I", meaning: "[hujan] berhenti" },
  { lesson: 32, kana: "はれます", kanji: "晴れます", type: "Kata Kerja II", meaning: "cerah" },
  { lesson: 32, kana: "くもります", kanji: "曇ります", type: "Kata Kerja I", meaning: "mendung" },
  { lesson: 32, kana: "つづきます", kanji: "続きます", context: "[ねつが〜]", type: "Kata Kerja I", meaning: "[demam] berlangsung" },
  { lesson: 32, kana: "ひきます", kanji: null, context: "[かぜを〜]", type: "Kata Kerja I", meaning: "masuk [angin]" },
  { lesson: 32, kana: "ひやします", kanji: "冷やします", type: "Kata Kerja I", meaning: "mendinginkan" },
  { lesson: 32, kana: "こみます", kanji: "込みます", context: "[みちが〜]", type: "Kata Kerja I", meaning: "[jalan] macet" },
  { lesson: 32, kana: "すきます", kanji: null, context: "[みちが〜]", type: "Kata Kerja I", meaning: "[jalan] sepi" },
  { lesson: 32, kana: "でます", kanji: "出ます", context: "[しあいに〜]", type: "Kata Kerja II", meaning: "mengikutsertakan [pertandingan]" },
  { lesson: 32, kana: "でます", kanji: "出ます", context: "[パーティーに〜]", type: "Kata Kerja II", meaning: "menghadiri [pesta]" },
  { lesson: 32, kana: "むりをします", kanji: "無理をします", type: "Kata Kerja III", meaning: "memaksakan diri" },
  { lesson: 32, kana: "じゅうぶん", kanji: "十分", type: "Kata Sifat", meaning: "dengan cukup" },
  { lesson: 32, kana: "おかしい", kanji: null, type: "Kata Sifat", meaning: "aneh, menarik" },
  { lesson: 32, kana: "うるさい", kanji: null, type: "Kata Sifat", meaning: "bising" },
  { lesson: 32, kana: "せんせい", kanji: "先生", type: "Kata Benda", meaning: "dokter" },
  { lesson: 32, kana: "やけど", kanji: null, type: "Kata Benda", meaning: "luka bakar (〜を します: menderita luka bakar)" },
  { lesson: 32, kana: "けが", kanji: null, type: "Kata Benda", meaning: "luka (〜を します: terluka)" },
  { lesson: 32, kana: "せき", kanji: null, type: "Kata Benda", meaning: "batuk (〜を します／〜が でます: batuk)" },
  { lesson: 32, kana: "インフルエンザ", kanji: null, type: "Kata Benda", meaning: "influenza" },
  { lesson: 32, kana: "そら", kanji: "空", type: "Kata Benda", meaning: "langit" },
  { lesson: 32, kana: "たいよう", kanji: "太陽", type: "Kata Benda", meaning: "matahari" },
  { lesson: 32, kana: "ほし", kanji: "星", type: "Kata Benda", meaning: "bintang" },
  { lesson: 32, kana: "かぜ", kanji: "風", type: "Kata Benda", meaning: "angin" },
  { lesson: 32, kana: "ひがし", kanji: "東", type: "Kata Benda", meaning: "timur" },
  { lesson: 32, kana: "にし", kanji: "西", type: "Kata Benda", meaning: "barat" },
  { lesson: 32, kana: "みなみ", kanji: "南", type: "Kata Benda", meaning: "selatan" },
  { lesson: 32, kana: "きた", kanji: "北", type: "Kata Benda", meaning: "utara" },
  { lesson: 32, kana: "こくさい〜", kanji: "国際〜", type: "Sufiks", meaning: "internasional 〜" },
  { lesson: 32, kana: "すいどう", kanji: "水道", type: "Kata Benda", meaning: "air PAM" },
  { lesson: 32, kana: "エンジン", kanji: null, type: "Kata Benda", meaning: "mesin" },
  { lesson: 32, kana: "チーム", kanji: null, type: "Kata Benda", meaning: "regu" },
  { lesson: 32, kana: "こんや", kanji: "今夜", type: "Kata Benda", meaning: "nanti malam, malam ini" },
  { lesson: 32, kana: "ゆうがた", kanji: "夕方", type: "Kata Benda", meaning: "sore" },
  { lesson: 32, kana: "まえ", kanji: null, type: "Kata Benda", meaning: "sebelum" },
  { lesson: 32, kana: "おそく", kanji: "遅く", type: "Kata Keterangan", meaning: "kemalaman" },
  { lesson: 32, kana: "こんなに", kanji: null, type: "Ungkapan", meaning: "begini" },
  { lesson: 32, kana: "そんなに", kanji: null, type: "Ungkapan", meaning: "begitu (mengenai barang atau hal tentang lawan bicara)" },
  { lesson: 32, kana: "あんなに", kanji: null, type: "Ungkapan", meaning: "begitu (mengenai barang atau hal tentang tidak ada hubungan dengan pembicara dan lawan bicara)" },

  { lesson: 32, kana: "げんき", kanji: "元気", type: "Kata Sifat", meaning: "sehat" },
  { lesson: 32, kana: "い", kanji: "胃", type: "Kata Benda", meaning: "lambung" },
  { lesson: 32, kana: "ストレス", kanji: null, type: "Kata Benda", meaning: "stres" },
  { lesson: 32, kana: "それはいけませんね。", kanji: null, type: "Ungkapan", meaning: "Kurang bagus." },

  { lesson: 32, kana: "ほしうらない", kanji: "星占い", type: "Kata Benda", meaning: "horoskop" },
  { lesson: 32, kana: "おうしざ", kanji: "牡牛座", type: "Kata Benda", meaning: "Taurus" },
  { lesson: 32, kana: "はたらきすぎ", kanji: "働きすぎ", type: "Kata Benda", meaning: "terlalu banyak pekerjaan" },
  { lesson: 32, kana: "こまります", kanji: "困ります", type: "Kata Kerja I", meaning: "bingung" },
  { lesson: 32, kana: "たからくじ", kanji: "宝くじ", type: "Kata Benda", meaning: "lotre" },
  { lesson: 32, kana: "あたります", kanji: "当たります", context: "[宝くじが〜]", type: "Kata Kerja I", meaning: "memenangi [lotre]" },
  { lesson: 32, kana: "けんこう", kanji: "健康", type: "Kata Benda", meaning: "kesehatan" },
  { lesson: 32, kana: "れんあい", kanji: "恋愛", type: "Kata Benda", meaning: "asmara" },
  { lesson: 32, kana: "こいびと", kanji: "恋人", type: "Kata Benda", meaning: "pacar" },
  { lesson: 32, kana: "ラッキーアイテム", kanji: null, type: "Kata Benda", meaning: "benda yang mujur" },
  { lesson: 32, kana: "いし", kanji: "石", type: "Kata Benda", meaning: "batu" }
];
